"""Argument parser wiring for the embedded AIWF CLI."""
from __future__ import annotations

import argparse

from .flow import cmd_status
from .ops_commands import (
    _cmd_arch_change_decide, _cmd_arch_change_help, _cmd_arch_change_list,
    _cmd_arch_change_request, _cmd_checkpoint_create, _cmd_checkpoint_list,
    _cmd_checkpoint_restore, _cmd_checkpoint_restore_plan, _cmd_checkpoint_show,
    _cmd_doctor, _cmd_export_report, _cmd_fix_loop_help, _cmd_fix_loop_open,
    _cmd_fix_loop_resolve, _cmd_fix_loop_status, _cmd_git_commit,
    _cmd_git_suggest, _cmd_git_summary, _cmd_install,
)
from .project_memory_commands import (
    _cmd_asset_init, _cmd_asset_refresh, _cmd_goal_decide, _cmd_goal_help,
    _cmd_goal_revise, _cmd_idea_capture, _cmd_idea_expire, _cmd_idea_help,
    _cmd_idea_list, _cmd_idea_promote, _cmd_memory_help, _cmd_memory_suggest,
    _cmd_project_bootstrap, _cmd_project_map_help, _cmd_project_map_init, _cmd_project_map_show,
    _cmd_project_map_summarize, _cmd_project_map_update, _cmd_rule_add,
    _cmd_rule_add_negative, _cmd_rule_global_candidate, _cmd_rule_help,
    _cmd_rule_list, _cmd_rule_retire,
)
from .plan_commands import (
    _cmd_plan_create, _cmd_plan_help, _cmd_plan_list, _cmd_plan_show,
    _cmd_plan_summarize, _cmd_plan_update,
)
from .quality_commands import (
    _cmd_capability_decide, _cmd_capability_list, _cmd_capability_plan_use,
    _cmd_capability_scan, _cmd_capability_show,
    _cmd_env_help, _cmd_env_scan, _cmd_env_show, _cmd_quality_digest, _cmd_quality_help,
    _cmd_quality_surface, _cmd_quality_surfaces, _cmd_workspace_scan,
)
from .recipe_commands import (
    _cmd_recipe_help, _cmd_recipe_list, _cmd_recipe_recommend, _cmd_recipe_show,
)
from .research_commands import (
    _cmd_research_help, _cmd_research_list, _cmd_research_promote, _cmd_research_record,
    _cmd_research_skip,
)
from .state_commands import (
    _cmd_cleanup_check, _cmd_disposition_adversarial, _cmd_mark_cleanup_fresh,
    _cmd_mark_cleanup_stale, _cmd_prepare_close, _cmd_rebuild_current_state,
    _cmd_record_meta_critique, _cmd_record_review, _cmd_record_role_evidence,
    _cmd_set_workflow_mode,
    _cmd_record_quality_brief, _cmd_record_quality_policy, _cmd_record_testing,
    _cmd_start_context, _cmd_state_help,
)
from .task_commands import (
    _cmd_task_activate, _cmd_task_close, _cmd_task_help, _cmd_task_plan,
    _cmd_task_status, _cmd_task_suspend,
)
from ..constants import VERSION

def build_parser(cmd_init) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="aiwf",
        description="AIWF — Embedded coding-shell workflow governance.",
        epilog="Primary path: aiwf install reasonix → reasonix code . → /skill aiwf-planner",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd")
    sub.required = False

    # ── primary embedded commands ──
    sub.add_parser("init", help="initialize compact embedded .aiwf state files").set_defaults(func=cmd_init)
    p_install = sub.add_parser("install", help="install AIWF embedded integration (skills, hooks, agents, state, scripts)")
    p_install.add_argument("mode", choices=["claude", "reasonix"], help="installation mode")
    p_install.add_argument("--force", action="store_true", help="force overwrite existing files")
    p_install.set_defaults(func=_cmd_install)
    sub.add_parser("doctor", help="check AIWF embedded installation health").set_defaults(func=_cmd_doctor)
    sub.add_parser("status", help="show AIWF embedded project status").set_defaults(func=cmd_status)
    sub.add_parser("export-report", help="generate AIWF summary report to .aiwf/reports/闭合报告.md").set_defaults(func=_cmd_export_report)
    p_state = sub.add_parser("state", help="AIWF state operations (record-quality-policy)")
    p_state_sub = p_state.add_subparsers(dest="state_cmd")
    p_qp = p_state_sub.add_parser("record-quality-policy", help="record quality policy in state.json (short keys only)")
    p_qp.add_argument("--task-type", required=True, help="task type key")
    p_qp.add_argument("--workflow-level", required=True, help="L0_direct|L1_review_light|L2_standard_team|L3_full_power")
    p_qp.add_argument("--risk-flag", action="append", default=[], dest="risk_flags", help="repeatable risk flags")
    p_qp.add_argument("--reason", default="", help="routing reason")
    p_qp.set_defaults(func=_cmd_record_quality_policy)
    p_qb = p_state_sub.add_parser("record-quality-brief", help="record task-specific quality brief in goal.json")
    p_qb.add_argument("--acceptance", action="append", default=[], dest="acceptance", help="repeatable acceptance criteria")
    p_qb.add_argument("--test-focus", action="append", default=[], dest="test_focus", help="repeatable test focus items")
    p_qb.add_argument("--review-focus", action="append", default=[], dest="review_focus", help="repeatable review focus items")
    p_qb.add_argument("--non-goal", action="append", default=[], dest="non_goals", help="repeatable non-goals")
    p_qb.add_argument("--escalation-trigger", action="append", default=[], dest="escalation_triggers", help="repeatable escalation triggers")
    p_qb.add_argument("--user-visible-outcome", default="", help="user-visible outcome for evaluation contract")
    p_qb.add_argument("--acceptance-criterion", action="append", default=[], dest="acceptance_criteria", help="repeatable acceptance criteria")
    p_qb.add_argument("--test-obligation", action="append", default=[], dest="test_obligations", help="repeatable test obligations")
    p_qb.add_argument("--review-obligation", action="append", default=[], dest="review_obligations", help="repeatable review obligations")
    p_qb.add_argument("--known-risk", action="append", default=[], dest="known_risks", help="repeatable known risks")
    p_qb.add_argument("--closure-question", default="", help="closure question for evaluation contract")
    p_qb.add_argument("--system-integration-obligation", action="append", default=[], dest="system_integration_obligations", help="repeatable system integration obligations")
    p_qb.add_argument("--target-structure", default="", help="target structure after this task")
    p_qb.add_argument("--module-boundary", action="append", default=[], dest="module_boundaries", help="repeatable module boundaries to preserve")
    p_qb.add_argument("--allowed-file", action="append", default=[], dest="allowed_files", help="repeatable files allowed to modify")
    p_qb.add_argument("--protected-file", action="append", default=[], dest="protected_files", help="repeatable files that must not change")
    p_qb.add_argument("--allowed-new-file", action="append", default=[], dest="allowed_new_files", help="repeatable new files allowed")
    p_qb.add_argument("--public-api-change", action="append", default=[], dest="public_api_changes", help="repeatable public API changes allowed")
    p_qb.add_argument("--integration-point", action="append", default=[], dest="integration_points", help="repeatable system integration points")
    p_qb.add_argument("--architecture-invariant", action="append", default=[], dest="architecture_invariants", help="repeatable architecture invariants")
    p_qb.add_argument("--forbidden-restructure", action="append", default=[], dest="forbidden_restructures", help="repeatable forbidden restructures")
    p_qb.add_argument("--architecture-risk", action="append", default=[], dest="architecture_risks", help="repeatable architecture risks")
    p_qb.add_argument("--migration-source-of-truth", default="", help="canonical source for the new architecture/mainline")
    p_qb.add_argument("--legacy-path", action="append", default=[], dest="legacy_paths", help="repeatable legacy path/entry that must be removed, redirected, or explicitly isolated")
    p_qb.add_argument("--legacy-term", action="append", default=[], dest="legacy_terms", help="repeatable old term/name that must be swept from the mainline")
    p_qb.add_argument("--default-entrypoint", action="append", default=[], dest="default_entrypoints", help="repeatable default command/entrypoint that must exercise the new architecture")
    p_qb.add_argument("--validator", action="append", default=[], dest="validators", help="repeatable validator/CI command that must validate the new structure")
    p_qb.add_argument("--sample-output", action="append", default=[], dest="sample_outputs", help="repeatable sample/output path that must align with the new structure")
    p_qb.add_argument("--surface-type", action="append", default=[], dest="surface_types", help="repeatable quality surface types")
    p_qb.set_defaults(func=_cmd_record_quality_brief)
    p_sc = p_state_sub.add_parser("start-context", help="create or update a context with dispatch fields")
    p_sc.add_argument("--context-id", required=True, help="context ID (e.g. CTX-001)")
    p_sc.add_argument("--label", default="", help="context label")
    p_sc.add_argument("--allowed-write", action="append", default=[], dest="allowed_write", help="repeatable allowed-write paths")
    p_sc.add_argument("--forbidden-write", action="append", default=[], dest="forbidden_write", help="repeatable forbidden-write paths")
    p_sc.add_argument("--note", default="", help="context note")
    p_sc.add_argument("--purpose", default="", help="why this context exists")
    p_sc.add_argument("--read-hint", action="append", default=[], dest="read_hints", help="repeatable advisory read hints")
    p_sc.add_argument("--non-goal", action="append", default=[], dest="non_goals", help="repeatable non-goals")
    p_sc.add_argument("--dependency", action="append", default=[], dest="dependencies", help="repeatable dependencies")
    p_sc.add_argument("--interface-contract", default="", help="module boundary expectation")
    p_sc.add_argument("--test-focus", action="append", default=[], dest="test_focus", help="repeatable test focus items")
    p_sc.add_argument("--review-focus", action="append", default=[], dest="review_focus", help="repeatable review focus items")
    p_sc.add_argument("--escalation-trigger", action="append", default=[], dest="escalation_triggers", help="repeatable escalation triggers")
    p_sc.set_defaults(func=_cmd_start_context)
    p_rt = p_state_sub.add_parser("record-testing", help="record testing results in testing.json")
    p_rt.add_argument("--context-id", default="", help="context ID")
    p_rt.add_argument("--status", required=True, choices=["missing","partial","adequate","passed","failed"], help="testing status")
    p_rt.add_argument("--command", action="append", default=[], dest="commands", help="repeatable test commands")
    p_rt.add_argument("--untested-risk", action="append", default=[], dest="untested_risks", help="repeatable untested risks")
    p_rt.add_argument("--coverage-summary", default="", help="coverage summary")
    p_rt.add_argument("--failure-summary", default="", help="failure summary (when status=failed)")
    p_rt.add_argument("--failed-obligation", action="append", default=[], dest="failed_obligations", help="repeatable failed obligations")
    p_rt.add_argument("--failed-command", action="append", default=[], dest="failed_commands", help="repeatable failed commands")
    p_rt.add_argument("--suspected-route", default="", choices=["executor","tester","planner","environment"], help="suspected failure route")
    p_rt.add_argument("--required-verification", action="append", default=[], dest="required_verification", help="repeatable required verification steps")
    p_rt.add_argument("--acceptance-coverage", action="append", default=[], dest="acceptance_coverage", help="repeatable acceptance coverage items")
    p_rt.add_argument("--system-coverage", action="append", default=[], dest="system_coverage", help="repeatable system integration coverage items")
    p_rt.add_argument("--validation-layer", action="append", default=[], dest="validation_layers", help="repeatable executed validation layers: targeted|full_regression|integration|real_usage")
    p_rt.add_argument("--full-suite-status", default="", choices=["","not_run","passed","failed","not_available","not_feasible"], help="full project regression suite result")
    p_rt.add_argument("--full-suite-reason", default="", help="why the full suite was unavailable/not feasible")
    p_rt.add_argument("--real-usage-status", default="", choices=["","not_run","passed","failed","not_available","not_feasible"], help="actual user-facing entrypoint validation result")
    p_rt.add_argument("--real-usage-reason", default="", help="actual command/API/UI path tested, or why it was unavailable/not feasible")
    p_rt.add_argument("--inferred-surface", action="append", default=[], dest="inferred_surfaces", help="repeatable inferred surface types (Tester found missing)")
    p_rt.add_argument("--missing-surface-note", action="append", default=[], dest="missing_surface_notes", help="repeatable notes on missing surfaces")
    p_rt.add_argument("--cross-task-risk", action="append", default=[], dest="cross_task_risks", help="repeatable cross-task quality risk observed by Tester")
    p_rt.add_argument("--testing-debt", action="append", default=[], dest="testing_debt", help="repeatable testing debt observation")
    p_rt.add_argument("--repeated-change-hotspot", action="append", default=[], dest="repeated_change_hotspots", help="repeatable repeated-change hotspot")
    p_rt.add_argument("--adversarial-mode", action="store_true", dest="adversarial_mode", help="Tester ran in adversarial mode")
    p_rt.set_defaults(func=_cmd_record_testing)
    p_rrv = p_state_sub.add_parser("record-review", help="record review results and reviewer evidence")
    p_rrv.add_argument("--result", required=True, choices=["accepted","needs_fix","needs_more_testing","evidence_insufficient","scope_violation","rejected"], help="review result")
    p_rrv.add_argument("--closure-allowed", action="store_true", help="allow closure when result=accepted")
    p_rrv.add_argument("--accepted-evidence-id", action="append", default=[], dest="accepted_evidence_ids", help="repeatable accepted evidence ID")
    p_rrv.add_argument("--rejected-evidence-id", action="append", default=[], dest="rejected_evidence_ids", help="repeatable rejected evidence ID")
    p_rrv.add_argument("--blocker", action="append", default=[], dest="blockers", help="repeatable blocker")
    p_rrv.add_argument("--adversarial-observation", action="append", default=[], dest="adversarial_observations", help="repeatable adversarial observation message")
    p_rrv.add_argument("--cleanup-status", default="", choices=["","fresh","needs_attention","stale","unknown"], help="cleanup status")
    p_rrv.add_argument("--structure-status", default="", choices=["","accepted","needs_attention","unknown"], help="structure status")
    p_rrv.add_argument("--summary", default="", help="short review evidence summary")
    p_rrv.add_argument("--context-id", default="", help="context ID")
    p_rrv.set_defaults(func=_cmd_record_review)
    p_re = p_state_sub.add_parser("record-role-evidence", help="record explicit role evidence when hooks cannot observe a subagent")
    p_re.add_argument("--role", required=True, choices=["executor","tester","reviewer","planner"], help="role that produced the evidence")
    p_re.add_argument("--summary", required=True, help="short evidence summary")
    p_re.add_argument("--command", default="", help="command or action observed")
    p_re.add_argument("--changed-file", action="append", default=[], dest="changed_files", help="repeatable changed file")
    p_re.add_argument("--session-id", default="", help="engine session id, if available")
    p_re.add_argument("--agent-id", default="", help="subagent id, if available")
    p_re.add_argument("--agent-type", default="", help="agent type, if available")
    p_re.add_argument("--context-id", default="", help="context ID")
    p_re.add_argument("--status", default="pending", choices=["pending","accepted","rejected"], help="initial evidence status")
    p_re.add_argument("--exit-code", default=0, type=int, help="command exit code")
    p_re.add_argument("--scan-git", action="store_true", help="attach current git working-tree changed files as corroborating evidence")
    p_re.set_defaults(func=_cmd_record_role_evidence)
    p_mcf = p_state_sub.add_parser("mark-cleanup-fresh", help="mark cleanup as fresh, clear stale items")
    p_mcf.add_argument("--note", action="append", default=[], dest="notes", help="repeatable resolved notes")
    p_mcf.set_defaults(func=_cmd_mark_cleanup_fresh)
    p_mcs = p_state_sub.add_parser("mark-cleanup-stale", help="mark cleanup as stale with items/blockers")
    p_mcs.add_argument("--stale-item", action="append", required=True, default=[], dest="stale_items", help="repeatable stale items")
    p_mcs.add_argument("--blocker", action="append", default=[], dest="blockers", help="repeatable blockers")
    p_mcs.add_argument("--note", action="append", default=[], dest="notes", help="repeatable notes")
    p_mcs.set_defaults(func=_cmd_mark_cleanup_stale)
    # ── cleanup check ──
    p_cc = sub.add_parser("cleanup", help="lifecycle cleanup check (check)")
    p_cc_sub = p_cc.add_subparsers(dest="cleanup_cmd")
    p_cc_sub.add_parser("check", help="run lifecycle cleanup check (read-only)").set_defaults(func=_cmd_cleanup_check)
    p_cc.set_defaults(func=_cmd_cleanup_check)
    p_pc = p_state_sub.add_parser("prepare-close", help="promote evidence + set close_attempt (does NOT declare success)")
    p_pc.set_defaults(func=_cmd_prepare_close)
    p_da = p_state_sub.add_parser("disposition-adversarial", help="disposition a single adversarial observation")
    p_da.add_argument("--id", required=True, dest="adv_id", help="adversarial observation ID (e.g. ADV-001)")
    p_da.add_argument("--disposition", required=True, choices=["ignored","accepted","deferred","brief_updated"], help="disposition")
    p_da.add_argument("--reason", required=True, help="disposition reason")
    p_da.add_argument("--disposed-by", default="planner", dest="disposed_by", help="who is disposing")
    p_da.set_defaults(func=_cmd_disposition_adversarial)
    p_mc = p_state_sub.add_parser("record-meta-critique", help="record structured Planner meta-critique")
    p_mc.add_argument("--summary", required=True, help="what the Planner concluded after reviewing adversarial observations")
    p_mc.set_defaults(func=_cmd_record_meta_critique)
    p_rcs = p_state_sub.add_parser("rebuild-current-state", help="mechanically rebuild .aiwf/reports/当前状态.md from state files + PROJECT-MAP")
    p_rcs.set_defaults(func=_cmd_rebuild_current_state)
    p_swm = p_state_sub.add_parser("set-workflow-mode", help="record uncertainty routing mode/pattern")
    p_swm.add_argument("--request-mode", required=True, choices=["discussion","clarification","research","spike","execution"], help="current request mode")
    p_swm.add_argument("--workflow-pattern", default="", choices=["","linear","clarification_first","research_first","spike_first","adversarial_early"], help="uncertainty handling pattern")
    p_swm.add_argument("--reason", default="", help="short reason")
    p_swm.add_argument("--external-research-required", action="store_true", help="flag external research requirement")
    p_swm.set_defaults(func=_cmd_set_workflow_mode)
    p_state.set_defaults(func=_cmd_state_help)
    # ── task plan artifacts ──
    p_plan = sub.add_parser("plan", help="task plan artifacts (create, update, show, summarize, list)")
    p_plan_sub = p_plan.add_subparsers(dest="plan_cmd")
    p_plc = p_plan_sub.add_parser("create", help="create .aiwf/plans/TASK.md")
    p_plc.add_argument("--task-id", required=True, help="task ID")
    p_plc.add_argument("--context-id", default="", help="context ID")
    p_plc.add_argument("--title", default="", help="plan title")
    p_plc.set_defaults(func=_cmd_plan_create)
    p_plu = p_plan_sub.add_parser("update", help="update one plan section")
    p_plu.add_argument("--task-id", required=True, help="task ID")
    p_plu.add_argument("--section", required=True, choices=["open-questions","decisions","scope","implementation","testing","review","evidence","checklist"], help="section key")
    p_plu.add_argument("--content", required=True, help="replacement section content")
    p_plu.set_defaults(func=_cmd_plan_update)
    p_pls = p_plan_sub.add_parser("show", help="show one task plan")
    p_pls.add_argument("task_id", help="task ID")
    p_pls.set_defaults(func=_cmd_plan_show)
    p_plsum = p_plan_sub.add_parser("summarize", help="summarize one task plan")
    p_plsum.add_argument("task_id", help="task ID")
    p_plsum.set_defaults(func=_cmd_plan_summarize)
    p_plan_sub.add_parser("list", help="list task plans").set_defaults(func=_cmd_plan_list)
    p_plan.set_defaults(func=_cmd_plan_help)
    p_task = sub.add_parser("task", help="flexible task ledger and execution-window gate")
    p_task_sub = p_task.add_subparsers(dest="task_cmd")
    p_tp = p_task_sub.add_parser("plan", help="create/update a ledger task without activating execution")
    p_tp.add_argument("task_id_pos", nargs="?", help="task ID, e.g. TASK-001")
    p_tp.add_argument("--task-id", default="", help="task ID, e.g. TASK-001")
    p_tp.add_argument("--title", default="", help="task title")
    p_tp.add_argument("--status", default="candidate", choices=["candidate","ready","active","blocked","suspended","closed","rejected"], help="task status")
    p_tp.add_argument("--dependency", action="append", default=[], dest="dependencies", help="repeatable dependency task ID")
    p_tp.add_argument("--allowed-write", action="append", default=[], dest="allowed_write", help="repeatable allowed write path")
    p_tp.add_argument("--parallel-safe", action="store_true", help="Planner verified independent parallel execution")
    p_tp.add_argument("--note", action="append", default=[], dest="notes", help="repeatable task note")
    p_tp.set_defaults(func=_cmd_task_plan)
    p_ta = p_task_sub.add_parser("activate", help="activate a task if execution-window gates pass")
    p_ta.add_argument("task_id", help="task ID")
    p_ta.set_defaults(func=_cmd_task_activate)
    p_tc = p_task_sub.add_parser("close", help="mark a ledger task closed")
    p_tc.add_argument("task_id", help="task ID")
    p_tc.add_argument("--note", default="", help="closure note")
    p_tc.set_defaults(func=_cmd_task_close)
    p_ts = p_task_sub.add_parser("suspend", help="suspend a task with a lightweight state snapshot")
    p_ts.add_argument("task_id", help="task ID")
    p_ts.add_argument("--note", default="", help="suspension note")
    p_ts.set_defaults(func=_cmd_task_suspend)
    p_task_sub.add_parser("status", help="show task ledger summary").set_defaults(func=_cmd_task_status)
    p_task.set_defaults(func=_cmd_task_help)
    # ── fix-loop ──
    p_fixloop = sub.add_parser("fixloop", help="open or resolve a fix-loop")
    p_fl_sub = p_fixloop.add_subparsers(dest="fixloop_cmd")
    p_fl_open = p_fl_sub.add_parser("open", help="open a fix-loop with route and required fixes")
    p_fl_open.add_argument("--route", required=True, choices=["executor","tester","planner","environment"], help="route the fix to executor/tester/planner/environment")
    p_fl_open.add_argument("--reason", required=True, help="reason for opening the fix-loop")
    p_fl_open.add_argument("--required-fix", action="append", default=[], dest="required_fixes", help="repeatable required fixes")
    p_fl_open.add_argument("--required-verification", action="append", default=[], dest="required_verification", help="repeatable required verification steps")
    p_fl_open.add_argument("--source", default="reviewer", help="who opened the fix-loop (default: reviewer)")
    p_fl_open.set_defaults(func=_cmd_fix_loop_open)
    p_fl_resolve = p_fl_sub.add_parser("resolve", help="resolve a fix-loop")
    p_fl_resolve.add_argument("--resolution", required=True, help="how the fix-loop was resolved")
    p_fl_resolve.add_argument("--source", default="reviewer", help="who resolved the fix-loop (default: reviewer)")
    p_fl_resolve.set_defaults(func=_cmd_fix_loop_resolve)
    p_fl_status = p_fl_sub.add_parser("status", help="show fix-loop status")
    p_fl_status.set_defaults(func=_cmd_fix_loop_status)
    p_fixloop.set_defaults(func=_cmd_fix_loop_help)
    # ── arch-change ──
    p_ac = sub.add_parser("arch-change", help="architecture change requests (request, list, decide)")
    p_ac_sub = p_ac.add_subparsers(dest="arch_change_cmd")
    p_ac_req = p_ac_sub.add_parser("request", help="request an architecture change")
    p_ac_req.add_argument("--source", required=True, choices=["executor","tester","reviewer","planner"], help="who is requesting")
    p_ac_req.add_argument("--reason", required=True, help="why the change is needed")
    p_ac_req.add_argument("--proposed-change", required=True, dest="proposed_change", help="what is proposed")
    p_ac_req.add_argument("--affected-file", action="append", default=[], dest="affected_files", help="repeatable affected files")
    p_ac_req.add_argument("--affected-module", action="append", default=[], dest="affected_modules", help="repeatable affected modules")
    p_ac_req.add_argument("--current-contract-gap", default="", dest="current_contract_gap", help="gap in current contract")
    p_ac_req.add_argument("--scope-impact", default="", dest="scope_impact", help="scope impact")
    p_ac_req.add_argument("--risk", default="", help="risk of the change")
    p_ac_req.add_argument("--user-decision-required", action="store_true", dest="user_decision_required", help="flag if user decision needed")
    p_ac_req.set_defaults(func=_cmd_arch_change_request)
    p_ac_list = p_ac_sub.add_parser("list", help="list architecture change requests")
    p_ac_list.set_defaults(func=_cmd_arch_change_list)
    p_ac_dec = p_ac_sub.add_parser("decide", help="decide on an architecture change request")
    p_ac_dec.add_argument("id", help="ACR ID (e.g. ACR-001)")
    p_ac_dec.add_argument("--status", required=True, choices=["approved","rejected","superseded"], help="decision status")
    p_ac_dec.add_argument("--decision", required=True, help="planner decision text")
    p_ac_dec.set_defaults(func=_cmd_arch_change_decide)
    p_ac.set_defaults(func=_cmd_arch_change_help)
    p_cap = sub.add_parser("capability", help="external capability registry (scan, list, show)")
    p_cap_sub = p_cap.add_subparsers(dest="cap_cmd")
    p_cap_sub.add_parser("scan", help="scan project for external capabilities, write registry").set_defaults(func=_cmd_capability_scan)
    p_cap_sub.add_parser("list", help="list discovered capabilities").set_defaults(func=_cmd_capability_list)
    p_cap_show = p_cap_sub.add_parser("show", help="show one capability")
    p_cap_show.add_argument("id", help="capability ID")
    p_cap_show.set_defaults(func=_cmd_capability_show)
    p_cap_use = p_cap_sub.add_parser("plan-use", help="mark an external capability as intended for current-cycle use")
    p_cap_use.add_argument("id", help="capability ID")
    p_cap_use.set_defaults(func=_cmd_capability_plan_use)
    p_cap_dec = p_cap_sub.add_parser("decide", help="record Planner decision for lifecycle-overlap capability use")
    p_cap_dec.add_argument("id", help="capability ID")
    p_cap_dec.add_argument("--decision", required=True, help="Planner decision allowing/rejecting this capability use")
    p_cap_dec.add_argument("--decided-by", default="planner", help="who made the decision")
    p_cap_dec.set_defaults(func=_cmd_capability_decide)
    p_cap.set_defaults(func=_cmd_capability_scan)
    # ── recipes ──
    p_recipe = sub.add_parser("recipe", help="workflow recipes (list, show, recommend)")
    p_recipe_sub = p_recipe.add_subparsers(dest="recipe_cmd")
    p_recipe_sub.add_parser("list", help="list workflow recipes").set_defaults(func=_cmd_recipe_list)
    p_rs = p_recipe_sub.add_parser("show", help="show one workflow recipe")
    p_rs.add_argument("name", help="recipe name")
    p_rs.set_defaults(func=_cmd_recipe_show)
    p_rr = p_recipe_sub.add_parser("recommend", help="recommend recipes from task type and risk flags")
    p_rr.add_argument("--task-type", default="", help="task type key")
    p_rr.add_argument("--risk-flag", action="append", default=[], dest="risk_flags", help="repeatable risk flag")
    p_rr.set_defaults(func=_cmd_recipe_recommend)
    p_recipe.set_defaults(func=_cmd_recipe_help)
    # ── external research ──
    p_research = sub.add_parser("research", help="external research evidence (record, list, promote)")
    p_research_sub = p_research.add_subparsers(dest="research_cmd")
    p_xr = p_research_sub.add_parser("record", help="record low-trust external research")
    p_xr.add_argument("--source", required=True, help="source/tool/person")
    p_xr.add_argument("--query", required=True, help="research query/question")
    p_xr.add_argument("--claim", action="append", default=[], dest="claims", help="repeatable claim")
    p_xr.add_argument("--link", action="append", default=[], dest="links", help="repeatable link")
    p_xr.add_argument("--time-window", default="", help="time window such as last30days")
    p_xr.add_argument("--confidence", default="low", choices=["low","medium","high"], help="confidence")
    p_xr.set_defaults(func=_cmd_research_record)
    p_xl = p_research_sub.add_parser("list", help="list research records")
    p_xl.add_argument("--include-promoted", action="store_true", default=True, help="include promoted records")
    p_xl.set_defaults(func=_cmd_research_list)
    p_xp = p_research_sub.add_parser("promote", help="promote research into Planner decision trace")
    p_xp.add_argument("id", help="research ID")
    p_xp.add_argument("--decision", required=True, help="Planner decision using this research")
    p_xp.add_argument("--promoted-by", default="planner", help="who promoted it")
    p_xp.set_defaults(func=_cmd_research_promote)
    p_xs = p_research_sub.add_parser("skip", help="explicitly skip required external research")
    p_xs.add_argument("--reason", required=True, help="why external research is intentionally skipped")
    p_xs.add_argument("--decided-by", default="planner", help="who made the skip decision")
    p_xs.set_defaults(func=_cmd_research_skip)
    p_research.set_defaults(func=_cmd_research_help)
    # ── env ──
    p_env = sub.add_parser("env", help="project environment profile (scan, show)")
    p_env_sub = p_env.add_subparsers(dest="env_cmd")
    p_env_sub.add_parser("scan", help="scan project environment, write profile").set_defaults(func=_cmd_env_scan)
    p_env_sub.add_parser("show", help="show environment profile").set_defaults(func=_cmd_env_show)
    p_env.set_defaults(func=_cmd_env_help)
    # ── quality ──
    p_qual = sub.add_parser("quality", help="quality surface obligations (surfaces, surface)")
    p_qual_sub = p_qual.add_subparsers(dest="quality_cmd")
    p_qual_sub.add_parser("surfaces", help="list known quality surfaces").set_defaults(func=_cmd_quality_surfaces)
    p_qual_sub.add_parser("digest", help="refresh cross-task quality digest").set_defaults(func=_cmd_quality_digest)
    p_qs = p_qual_sub.add_parser("surface", help="show obligations for a surface")
    p_qs.add_argument("name", help="surface name (e.g. api_endpoint)")
    p_qs.set_defaults(func=_cmd_quality_surface)
    p_qual.set_defaults(func=_cmd_quality_help)
    # ── idea ──
    p_idea = sub.add_parser("idea", help="idea inbox (capture, list, promote, expire)")
    p_idea_sub = p_idea.add_subparsers(dest="idea_cmd")
    p_ic = p_idea_sub.add_parser("capture", help="capture a new idea")
    p_ic.add_argument("--text", required=True, help="idea text (short)")
    p_ic.add_argument("--tag", action="append", default=[], dest="tags", help="repeatable tags")
    p_ic.add_argument("--source", default="user", help="source (default: user)")
    p_ic.add_argument("--expires-days", type=int, default=14, dest="expires_days", help="days until expiry (default: 14)")
    p_ic.set_defaults(func=_cmd_idea_capture)
    p_il = p_idea_sub.add_parser("list", help="list active ideas")
    p_il.add_argument("--include-expired", action="store_true", dest="include_expired", help="include expired ideas")
    p_il.set_defaults(func=_cmd_idea_list)
    p_ip = p_idea_sub.add_parser("promote", help="promote an idea to adopted")
    p_ip.add_argument("id", help="idea ID")
    p_ip.add_argument("--target", default="", help="promotion target (project-map/goal/decision/architecture/followup)")
    p_ip.add_argument("--note", default="", help="promotion note")
    p_ip.set_defaults(func=_cmd_idea_promote)
    p_ie = p_idea_sub.add_parser("expire", help="expire an idea")
    p_ie.add_argument("id", help="idea ID")
    p_ie.add_argument("--reason", default="", help="expiry reason")
    p_ie.set_defaults(func=_cmd_idea_expire)
    p_idea.set_defaults(func=_cmd_idea_help)
    # ── rule ──
    p_rule = sub.add_parser("rule", help="project rules (add, add-negative, list, retire, global-candidate)")
    p_rule_sub = p_rule.add_subparsers(dest="rule_cmd")
    p_ra = p_rule_sub.add_parser("add", help="add a project rule")
    p_ra.add_argument("--text", required=True, help="rule text")
    p_ra.add_argument("--source", default="", help="source/context")
    p_ra.add_argument("--tag", action="append", default=[], dest="tags", help="repeatable tags")
    p_ra.set_defaults(func=_cmd_rule_add)
    p_rn = p_rule_sub.add_parser("add-negative", help="add a negative rule / guardrail")
    p_rn.add_argument("--text", required=True, help="rule text")
    p_rn.add_argument("--source", default="", help="source/context")
    p_rn.add_argument("--tag", action="append", default=[], dest="tags", help="repeatable tags")
    p_rn.set_defaults(func=_cmd_rule_add_negative)
    p_rule_sub.add_parser("list", help="list active rules").set_defaults(func=_cmd_rule_list)
    p_rr = p_rule_sub.add_parser("retire", help="retire a rule")
    p_rr.add_argument("id", help="rule ID")
    p_rr.add_argument("--reason", default="", help="retirement reason")
    p_rr.set_defaults(func=_cmd_rule_retire)
    p_rg = p_rule_sub.add_parser("global-candidate", help="mark a rule as global lesson candidate")
    p_rg.add_argument("id", help="rule ID")
    p_rg.add_argument("--note", default="", help="candidate note")
    p_rg.set_defaults(func=_cmd_rule_global_candidate)
    p_rule.set_defaults(func=_cmd_rule_help)
    # ── project-map ──
    p_pm = sub.add_parser("project-map", help="project map (init, show, update, summarize)")
    p_pm_sub = p_pm.add_subparsers(dest="pm_cmd")
    p_pm_sub.add_parser("init", help="create PROJECT-MAP.md").set_defaults(func=_cmd_project_map_init)
    p_pm_sub.add_parser("show", help="display PROJECT-MAP.md").set_defaults(func=_cmd_project_map_show)
    p_pmb = p_pm_sub.add_parser("bootstrap", help="bootstrap AIWF assets from existing project code")
    p_pmb.set_defaults(func=_cmd_project_bootstrap)
    p_pmu = p_pm_sub.add_parser("update", help="update a section of PROJECT-MAP.md")
    p_pmu.add_argument("--section", required=True, choices=["snapshot","current-stage","completed-milestones","active-direction","next-candidate-tasks","architecture-direction","environment-summary","open-decisions","deferred-risks","rejected-routes","ideas-to-review"], help="section to update")
    p_pmu.add_argument("--text", required=True, help="new content for the section")
    p_pmu.set_defaults(func=_cmd_project_map_update)
    p_pm_sub.add_parser("summarize", help="show short summary of PROJECT-MAP.md").set_defaults(func=_cmd_project_map_summarize)
    p_pm.set_defaults(func=_cmd_project_map_help)
    p_mem = sub.add_parser("memory", help="advisory lesson retrieval (suggest)")
    p_mem_sub = p_mem.add_subparsers(dest="mem_cmd")
    p_ms = p_mem_sub.add_parser("suggest", help="suggest relevant lessons for current task")
    p_ms.add_argument("--goal", default="", help="task goal for matching")
    p_ms.add_argument("--task-type", default="", help="task type key for matching")
    p_ms.add_argument("--file", action="append", default=[], dest="files", help="repeatable file paths")
    p_ms.add_argument("--limit", type=int, default=5, help="max results per category")
    p_ms.set_defaults(func=_cmd_memory_suggest)
    p_mem.set_defaults(func=_cmd_memory_help)
    p_git = sub.add_parser("git", help="git commit safety (summary, suggest, commit)")
    p_git_sub = p_git.add_subparsers(dest="git_cmd")
    p_git_sub.add_parser("summary", help="show git working tree summary").set_defaults(func=_cmd_git_summary)
    p_git_sub.add_parser("suggest-commit", help="suggest a commit message").set_defaults(func=_cmd_git_suggest)
    p_gc = p_git_sub.add_parser("commit", help="commit with confirmation (requires --confirm)")
    p_gc.add_argument("--message", required=True, help="commit message")
    p_gc.add_argument("--confirm", action="store_true", help="confirm commit")
    p_gc.add_argument("--include-governance", action="store_true", help="also commit governance files")
    p_gc.set_defaults(func=_cmd_git_commit)
    p_git.set_defaults(func=_cmd_git_summary)
    p_ck = sub.add_parser("checkpoint", help="rollback checkpoint (create, list, show, restore)")
    p_ck_sub = p_ck.add_subparsers(dest="ck_cmd")
    p_ck_cr = p_ck_sub.add_parser("create", help="create a rollback checkpoint")
    p_ck_cr.add_argument("--label", default="", help="checkpoint label")
    p_ck_cr.add_argument("--include-governance", dest="include_gov", action="store_true", default=True)
    p_ck_cr.add_argument("--no-include-governance", dest="include_gov", action="store_false")
    p_ck_cr.add_argument("--mode", choices=["patch","stash"], default="patch", help="checkpoint mode")
    p_ck_cr.set_defaults(func=_cmd_checkpoint_create)
    p_ck_sub.add_parser("list", help="list checkpoints").set_defaults(func=_cmd_checkpoint_list)
    p_ck_show = p_ck_sub.add_parser("show", help="show checkpoint metadata")
    p_ck_show.add_argument("id", help="checkpoint ID")
    p_ck_show.set_defaults(func=_cmd_checkpoint_show)
    p_ck_plan = p_ck_sub.add_parser("restore-plan", help="show restore plan")
    p_ck_plan.add_argument("id", help="checkpoint ID")
    p_ck_plan.set_defaults(func=_cmd_checkpoint_restore_plan)
    p_ck_restore = p_ck_sub.add_parser("restore", help="restore to checkpoint (requires --confirm)")
    p_ck_restore.add_argument("id", help="checkpoint ID")
    p_ck_restore.add_argument("--confirm", action="store_true", help="confirm restore")
    p_ck_restore.set_defaults(func=_cmd_checkpoint_restore)
    p_ck.set_defaults(func=_cmd_checkpoint_list)
    p_goal = sub.add_parser("goal", help="goal thread / intent revision operations")
    p_goal_sub = p_goal.add_subparsers(dest="goal_cmd")
    p_gr = p_goal_sub.add_parser("revise", help="revise current goal with intent tracking")
    p_gr.add_argument("--new-goal", required=True, help="new goal text")
    p_gr.add_argument("--reason", required=True, help="reason for revision")
    p_gr.add_argument("--decision", default="", help="associated decision")
    p_gr.add_argument("--source", default="user", help="source of revision")
    p_gr.set_defaults(func=_cmd_goal_revise)
    p_gd = p_goal_sub.add_parser("decide", help="record a goal-level decision")
    p_gd.add_argument("--decision", required=True, help="decision text")
    p_gd.add_argument("--source", default="user", help="source of decision")
    p_gd.set_defaults(func=_cmd_goal_decide)
    p_goal.set_defaults(func=_cmd_goal_help)
    p_ws = sub.add_parser("workspace", help="workspace drift scan")
    p_ws_sub = p_ws.add_subparsers(dest="ws_cmd")
    p_ws_scan = p_ws_sub.add_parser("scan", help="scan workspace for untracked/modified files")
    p_ws_scan.add_argument("--fix", action="store_true", help="auto-update baseline after detecting changes")
    p_ws_scan.set_defaults(func=_cmd_workspace_scan)
    p_asset = sub.add_parser("asset", help="context asset layer commands (init, refresh)")
    p_asset_sub = p_asset.add_subparsers(dest="asset_cmd")
    p_asset_sub.add_parser("init", help="initialize .aiwf/assets/ with project-map, test-map, conventions").set_defaults(func=_cmd_asset_init)
    p_asset_refresh = p_asset_sub.add_parser("refresh", help="check or update asset freshness")
    p_asset_refresh.add_argument("--check", action="store_true", default=True, help="check freshness only (default)")
    p_asset_refresh.add_argument("--update", action="store_true", help="update hashes for changed files")
    p_asset_refresh.set_defaults(func=_cmd_asset_refresh)
    p_asset.set_defaults(func=_cmd_asset_init)

    return parser
