"""Argument parser wiring for the embedded AIWF CLI."""
from __future__ import annotations

import argparse

from .flow import cmd_next, cmd_status
from .ops_commands import (
    _cmd_arch_change_decide, _cmd_arch_change_help, _cmd_arch_change_list,
    _cmd_arch_change_request, _cmd_audit_archive, _cmd_checkpoint_create,
    _cmd_checkpoint_list, _cmd_checkpoint_restore, _cmd_checkpoint_restore_plan,
    _cmd_checkpoint_show, _cmd_doctor, _cmd_fix_loop_help, _cmd_fix_loop_open,
    _cmd_fix_loop_repair, _cmd_fix_loop_resolve, _cmd_fix_loop_revalidate,
    _cmd_fix_loop_status, _cmd_git_commit,
    _cmd_git_suggest, _cmd_git_summary, _cmd_install,
)
from .project_memory_commands import (
    _cmd_asset_init, _cmd_asset_refresh, _cmd_goal_decide, _cmd_goal_help,
    _cmd_goal_revise, _cmd_idea_capture, _cmd_idea_expire, _cmd_idea_help,
    _cmd_idea_list, _cmd_idea_promote, _cmd_memory_help, _cmd_memory_suggest,
    _cmd_project_bootstrap, _cmd_project_map_help, _cmd_project_map_init, _cmd_project_map_show,
    _cmd_project_map_bind, _cmd_project_map_relations, _cmd_project_map_summarize,
    _cmd_project_map_unbind, _cmd_project_map_update, _cmd_project_map_validate, _cmd_rule_add,
    _cmd_rule_add_negative, _cmd_rule_global_candidate, _cmd_rule_help,
    _cmd_rule_list, _cmd_rule_retire,
)
from .admission_commands import (
    _cmd_change_admit, _cmd_change_help, _cmd_change_prepare, _cmd_change_validate_decision,
)
from .architecture_doc_commands import (
    _cmd_architecture_doc_help, _cmd_architecture_doc_require,
    _cmd_architecture_doc_satisfy, _cmd_architecture_doc_status,
    _cmd_architecture_doc_validate, _cmd_architecture_doc_waive,
)
from .foundation_commands import (
    _cmd_foundation_validate,
)
from .frontier_commands import (
    _cmd_frontier_help, _cmd_frontier_prepare, _cmd_frontier_validate,
)
from .plan_commands import (
    _cmd_plan_activate, _cmd_plan_attach, _cmd_plan_create, _cmd_plan_deactivate,
    _cmd_plan_dep_add, _cmd_plan_dep_remove, _cmd_plan_dep_show,
    _cmd_plan_detach, _cmd_plan_help, _cmd_plan_list, _cmd_plan_show,
    _cmd_plan_summarize, _cmd_plan_update,
)
from .layout_commands import _cmd_workspace_migrate_layout
from .quality_commands import (
    _cmd_capability_decide, _cmd_capability_list, _cmd_capability_plan_use,
    _cmd_capability_scan, _cmd_capability_show,
    _cmd_env_help, _cmd_env_scan, _cmd_env_show, _cmd_quality_digest, _cmd_quality_help,
    _cmd_quality_surface, _cmd_quality_surfaces, _cmd_workspace_scan,
)
from .recipe_commands import (
    _cmd_recipe_help, _cmd_recipe_list, _cmd_recipe_recommend, _cmd_recipe_show,
)
from .research_commands import (
    _cmd_research_help, _cmd_research_list, _cmd_research_promote, _cmd_research_record,
    _cmd_research_skip,
)
from .state_commands import (
    _cmd_cleanup_check, _cmd_disposition_adversarial, _cmd_mark_cleanup_fresh,
    _cmd_mark_cleanup_stale, _cmd_prepare_close, _cmd_cancel_close,
    _cmd_record_architecture_review, _cmd_record_meta_critique,
    _cmd_record_review, _cmd_record_role_evidence,
    _cmd_set_goal_confirmed, _cmd_set_planner_inline, _cmd_set_workflow_mode,
    _cmd_record_quality_brief, _cmd_record_quality_policy, _cmd_record_testing,
    _cmd_start_context, _cmd_state_help,
)
from .claims_commands import (
    _cmd_claim_help, _cmd_claim_list, _cmd_claim_record, _cmd_claim_verify,
)
from .goal_tree_commands import (
    _cmd_goal_tree_add, _cmd_goal_tree_graft, _cmd_goal_tree_help,
    _cmd_goal_tree_impact, _cmd_goal_tree_init_root, _cmd_goal_tree_list,
    _cmd_goal_tree_list_temporary, _cmd_goal_tree_prune, _cmd_goal_tree_show,
    _cmd_goal_tree_validate,
    _cmd_relation_add, _cmd_relation_remove, _cmd_relation_show,
)
from .milestone_commands import (
    _cmd_milestone_arch_review, _cmd_milestone_assess, _cmd_milestone_close,
    _cmd_milestone_confirm, _cmd_milestone_create, _cmd_milestone_help, _cmd_milestone_integration_test,
    _cmd_milestone_list, _cmd_milestone_show, _cmd_milestone_update,
)
from .mission_commands import (
    _cmd_mission_help, _cmd_mission_show, _cmd_mission_update,
)
from .route_commands import (
    _cmd_route_downgrade, _cmd_route_explain, _cmd_route_help,
    _cmd_route_substitute,
)
from .task_commands import (
    _cmd_task_activate, _cmd_task_close, _cmd_task_confirm_start, _cmd_task_help, _cmd_task_plan,
    _cmd_task_status, _cmd_task_suspend,
)
from ..constants import VERSION

def build_parser(cmd_init) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="aiwf",
        description="AIWF — Embedded coding-shell workflow governance.",
        epilog="Primary path: aiwf install claude (or reasonix)",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd")
    sub.required = False

    # ── primary embedded commands ──
    sub.add_parser("init", help="initialize compact embedded .aiwf state files").set_defaults(func=cmd_init)
    p_install = sub.add_parser("install", help="install AIWF embedded integration (skills, hooks, agents, state, scripts)")
    p_install.add_argument("mode", choices=["claude", "reasonix"], help="installation mode")
    p_install.add_argument("--force", action="store_true", help="force overwrite existing files")
    p_install.set_defaults(func=_cmd_install)
    sub.add_parser("doctor", help="check AIWF embedded installation health").set_defaults(func=_cmd_doctor)
    p_status = sub.add_parser("status", help="show AIWF embedded project status (human short default; --prompt for AI, --debug for full)")
    p_status.add_argument("--prompt", action="store_true", help="AI prompt injection format (~10 lines)")
    p_status.add_argument("--debug", action="store_true", help="full debug panel with all sections")
    p_status.set_defaults(func=cmd_status)
    p_next = sub.add_parser("next", help="show machine-readable next-action directive for current phase")
    p_next.add_argument("--role", help="frame output for a specific role (planner|executor|tester|reviewer)", default="")
    p_next.set_defaults(func=cmd_next)

    # ── architecture snapshot ──
    p_arch_doc = sub.add_parser("architecture-doc", help="architecture snapshot requirement contract")
    p_arch_doc_sub = p_arch_doc.add_subparsers(dest="architecture_doc_cmd")
    p_adr = p_arch_doc_sub.add_parser("require", help="mark architecture snapshot as required")
    p_adr.add_argument("--reason", required=True, help="why the snapshot is required")
    p_adr.add_argument("--path", default=".aiwf/artifacts/reports/架构详细设计.md", help="snapshot path")
    p_adr.set_defaults(func=_cmd_architecture_doc_require)
    p_arch_doc_sub.add_parser("status", help="show architecture snapshot status").set_defaults(func=_cmd_architecture_doc_status)
    p_adv = p_arch_doc_sub.add_parser("validate", help="validate architecture snapshot structure")
    p_adv.add_argument("--path", default="", help="snapshot path override")
    p_adv.set_defaults(func=_cmd_architecture_doc_validate)
    p_ads = p_arch_doc_sub.add_parser("satisfy", help="validate and mark snapshot requirement satisfied")
    p_ads.add_argument("--path", default="", help="snapshot path override")
    p_ads.set_defaults(func=_cmd_architecture_doc_satisfy)
    p_adw = p_arch_doc_sub.add_parser("waive", help="waive snapshot requirement with reason")
    p_adw.add_argument("--reason", required=True, help="why the snapshot is not required now")
    p_adw.set_defaults(func=_cmd_architecture_doc_waive)
    p_arch_doc.set_defaults(func=_cmd_architecture_doc_help)

    p_state = sub.add_parser("state", help="AIWF state operations (record-quality-policy)")
    p_state_sub = p_state.add_subparsers(dest="state_cmd")
    p_qp = p_state_sub.add_parser("record-quality-policy", help="record quality policy in state.json (short keys only)")
    p_qp.add_argument("--task-type", required=True, help="task type key")
    p_qp.add_argument("--workflow-level", required=True, help="L0_direct|L1_review_light|L2_standard_team|L3_full_power")
    p_qp.add_argument("--risk-flag", action="append", default=[], dest="risk_flags", help="repeatable risk flags")
    p_qp.add_argument("--reason", default="", help="routing reason")
    p_qp.set_defaults(func=_cmd_record_quality_policy)
    p_qb = p_state_sub.add_parser("record-quality-brief", help="record task-specific quality brief in goal.json")
    p_qb.add_argument("--acceptance", action="append", default=[], dest="acceptance", help="repeatable acceptance criteria")
    p_qb.add_argument("--test-focus", action="append", default=[], dest="test_focus", help="repeatable test focus items")
    p_qb.add_argument("--review-focus", action="append", default=[], dest="review_focus", help="repeatable review focus items")
    p_qb.add_argument("--non-goal", action="append", default=[], dest="non_goals", help="repeatable non-goals")
    p_qb.add_argument("--escalation-trigger", action="append", default=[], dest="escalation_triggers", help="repeatable escalation triggers")
    p_qb.add_argument("--user-visible-outcome", default="", help="user-visible outcome for evaluation contract")
    p_qb.add_argument("--acceptance-criterion", action="append", default=[], dest="acceptance_criteria", help="repeatable acceptance criteria")
    p_qb.add_argument("--test-obligation", action="append", default=[], dest="test_obligations", help="repeatable test obligations")
    p_qb.add_argument("--review-obligation", action="append", default=[], dest="review_obligations", help="repeatable review obligations")
    p_qb.add_argument("--known-risk", action="append", default=[], dest="known_risks", help="repeatable known risks")
    p_qb.add_argument("--closure-question", default="", help="closure question for evaluation contract")
    p_qb.add_argument("--system-integration-obligation", action="append", default=[], dest="system_integration_obligations", help="repeatable system integration obligations")
    p_qb.add_argument("--target-structure", default="", help="target structure after this task")
    p_qb.add_argument("--module-boundary", action="append", default=[], dest="module_boundaries", help="repeatable module boundaries to preserve")
    p_qb.add_argument("--allowed-file", action="append", default=[], dest="allowed_files", help="repeatable files allowed to modify")
    p_qb.add_argument("--protected-file", action="append", default=[], dest="protected_files", help="repeatable files that must not change")
    p_qb.add_argument("--allowed-new-file", action="append", default=[], dest="allowed_new_files", help="repeatable new files allowed")
    p_qb.add_argument("--public-api-change", action="append", default=[], dest="public_api_changes", help="repeatable public API changes allowed")
    p_qb.add_argument("--integration-point", action="append", default=[], dest="integration_points", help="repeatable system integration points")
    p_qb.add_argument("--architecture-invariant", action="append", default=[], dest="architecture_invariants", help="repeatable architecture invariants")
    p_qb.add_argument("--forbidden-restructure", action="append", default=[], dest="forbidden_restructures", help="repeatable forbidden restructures")
    p_qb.add_argument("--architecture-risk", action="append", default=[], dest="architecture_risks", help="repeatable architecture risks")
    p_qb.add_argument("--migration-source-of-truth", default="", help="canonical source for the new architecture/mainline")
    p_qb.add_argument("--legacy-path", action="append", default=[], dest="legacy_paths", help="repeatable legacy path/entry that must be removed, redirected, or explicitly isolated")
    p_qb.add_argument("--legacy-term", action="append", default=[], dest="legacy_terms", help="repeatable old term/name that must be swept from the mainline")
    p_qb.add_argument("--default-entrypoint", action="append", default=[], dest="default_entrypoints", help="repeatable default command/entrypoint that must exercise the new architecture")
    p_qb.add_argument("--validator", action="append", default=[], dest="validators", help="repeatable validator/CI command that must validate the new structure")
    p_qb.add_argument("--sample-output", action="append", default=[], dest="sample_outputs", help="repeatable sample/output path that must align with the new structure")
    p_qb.add_argument("--surface-type", action="append", default=[], dest="surface_types", help="repeatable quality surface types")
    p_qb.set_defaults(func=_cmd_record_quality_brief)
    p_sc = p_state_sub.add_parser("start-context", help="create or update an advisory context (scope lives on Plan)")
    p_sc.add_argument("--context-id", required=True, help="context ID (e.g. CTX-001)")
    p_sc.add_argument("--label", default="", help="context label")
    p_sc.add_argument("--note", default="", help="context note")
    p_sc.add_argument("--purpose", default="", help="why this context exists")
    p_sc.add_argument("--read-hint", action="append", default=[], dest="read_hints", help="repeatable advisory read hints")
    p_sc.add_argument("--non-goal", action="append", default=[], dest="non_goals", help="repeatable non-goals")
    p_sc.add_argument("--dependency", action="append", default=[], dest="dependencies", help="repeatable dependencies")
    p_sc.add_argument("--interface-contract", default="", help="module boundary expectation")
    p_sc.add_argument("--test-focus", action="append", default=[], dest="test_focus", help="repeatable test focus items")
    p_sc.add_argument("--review-focus", action="append", default=[], dest="review_focus", help="repeatable review focus items")
    p_sc.add_argument("--escalation-trigger", action="append", default=[], dest="escalation_triggers", help="repeatable escalation triggers")
    p_sc.set_defaults(func=_cmd_start_context)
    p_rt = p_state_sub.add_parser("record-testing", help="record testing results in testing.json")
    p_rt.add_argument("--context-id", default="", help="context ID")
    p_rt.add_argument("--status", required=True, choices=["missing","partial","adequate","passed","failed"], help="testing status")
    p_rt.add_argument("--command", action="append", default=[], dest="commands", help="repeatable test commands")
    p_rt.add_argument("--untested-risk", action="append", default=[], dest="untested_risks", help="repeatable untested risks")
    p_rt.add_argument("--coverage-summary", default="", help="coverage summary")
    p_rt.add_argument("--failure-summary", default="", help="failure summary (when status=failed)")
    p_rt.add_argument("--failed-obligation", action="append", default=[], dest="failed_obligations", help="repeatable failed obligations")
    p_rt.add_argument("--failed-command", action="append", default=[], dest="failed_commands", help="repeatable failed commands")
    p_rt.add_argument("--suspected-route", default="", choices=["executor","tester","planner","environment"], help="suspected failure route")
    p_rt.add_argument("--required-verification", action="append", default=[], dest="required_verification", help="repeatable required verification steps")
    p_rt.add_argument("--acceptance-coverage", action="append", default=[], dest="acceptance_coverage", help="repeatable acceptance coverage items")
    p_rt.add_argument("--system-coverage", action="append", default=[], dest="system_coverage", help="repeatable system integration coverage items")
    p_rt.add_argument("--validation-layer", action="append", default=[], dest="validation_layers", help="repeatable executed validation layers: targeted|full_regression|integration|real_usage")
    p_rt.add_argument("--full-suite-status", default="", choices=["","not_run","passed","failed","not_available","not_feasible"], help="full project regression suite result")
    p_rt.add_argument("--full-suite-reason", default="", help="why the full suite was unavailable/not feasible")
    p_rt.add_argument("--real-usage-status", default="", choices=["","not_run","passed","failed","not_available","not_feasible"], help="actual user-facing entrypoint validation result")
    p_rt.add_argument("--real-usage-reason", default="", help="actual command/API/UI path tested, or why it was unavailable/not feasible")
    p_rt.add_argument("--inferred-surface", action="append", default=[], dest="inferred_surfaces", help="repeatable inferred surface types (Tester found missing)")
    p_rt.add_argument("--missing-surface-note", action="append", default=[], dest="missing_surface_notes", help="repeatable notes on missing surfaces")
    p_rt.add_argument("--cross-task-risk", action="append", default=[], dest="cross_task_risks", help="repeatable cross-task quality risk observed by Tester")
    p_rt.add_argument("--testing-debt", action="append", default=[], dest="testing_debt", help="repeatable testing debt observation")
    p_rt.add_argument("--repeated-change-hotspot", action="append", default=[], dest="repeated_change_hotspots", help="repeatable repeated-change hotspot")
    p_rt.add_argument("--evidence-id", action="append", default=[], dest="evidence_ids", help="repeatable evidence ID backing test results (preferred over --command)")
    p_rt.add_argument("--adversarial-mode", action="store_true", dest="adversarial_mode", help="Tester ran in adversarial mode")
    p_rt.add_argument("--delta-verification", default="", help="delta verification narrative — what was re-verified vs reused")
    p_rt.add_argument("--reused-evidence-id", action="append", default=[], dest="reused_evidence_ids", help="repeatable evidence IDs reused from prior testing")
    p_rt.add_argument("--invalidated-evidence-id", action="append", default=[], dest="invalidated_evidence_ids", help="repeatable evidence IDs invalidated by this fix")
    p_rt.add_argument("--supports-plan", default="", dest="supports_plan", help="PLAN-ID this testing evidence supports")
    p_rt.add_argument("--supports-goal", default="", dest="supports_goal", help="GOAL-ID this testing evidence supports")
    p_rt.add_argument("--force", action="store_true", help="allow same-session testing on L2+ (Planner inline execution only)")
    p_rt.set_defaults(func=_cmd_record_testing)
    p_rrv = p_state_sub.add_parser("record-review", help="record review results and reviewer evidence (V2: use --verdict for quality outcome)")
    p_rrv.add_argument("--verdict", default="", choices=["","PASS","PASS_WITH_RISK","REVISE","REJECT"], help="V2 quality verdict (derives result + closure)")
    p_rrv.add_argument("--result", default="", choices=["","accepted","needs_fix","needs_more_testing","evidence_insufficient","scope_violation","rejected"], help="V1 review result (use --verdict for V2)")
    p_rrv.add_argument("--dimension-score", action="append", default=[], dest="dimension_scores", metavar="NAME=PASS|RISK|FAIL", help="repeatable dimension score: requirement_fit, architecture_fit, minimality, correctness, test_adequacy, maintainability, risk_debt, human_trust")
    p_rrv.add_argument("--dimension-note", action="append", default=[], dest="dimension_notes", metavar="NAME_NOTE=text", help="repeatable dimension note (e.g. correctness_note=logic verified)")
    p_rrv.add_argument("--basis-status", action="append", default=[], dest="basis_statuses", metavar="NAME=covered|gap|not_applicable", help="repeatable review basis status for goal/plan/scope/evidence/testing/impact")
    p_rrv.add_argument("--basis-note", action="append", default=[], dest="basis_notes", metavar="NAME_NOTE=text", help="repeatable review basis note (required for gap/not_applicable)")
    p_rrv.add_argument("--closure-allowed", action="store_true", help="allow closure when result=accepted")
    p_rrv.add_argument("--accepted-evidence-id", action="append", default=[], dest="accepted_evidence_ids", help="repeatable accepted evidence ID")
    p_rrv.add_argument("--rejected-evidence-id", action="append", default=[], dest="rejected_evidence_ids", help="repeatable rejected evidence ID")
    p_rrv.add_argument("--blocker", action="append", default=[], dest="blockers", help="repeatable blocker")
    p_rrv.add_argument("--adversarial-observation", action="append", default=[], dest="adversarial_observations", help="repeatable SEVERITY:::KIND:::MESSAGE (plain text remains warn)")
    p_rrv.add_argument("--resolution", default="", help="required when clearing a prior REVISE/REJECT review")
    p_rrv.add_argument("--resolution-evidence-id", action="append", default=[], dest="resolution_evidence_ids", help="repeatable evidence proving review blockers were fixed")
    p_rrv.add_argument("--cleanup-status", default="", choices=["","fresh","needs_attention","stale","unknown"], help="cleanup status")
    p_rrv.add_argument("--structure-status", default="", choices=["","accepted","needs_attention","unknown"], help="structure status")
    p_rrv.add_argument("--cleanup-code", default="", choices=["","clean","needs_work","not_applicable"], help="code cleanliness check")
    p_rrv.add_argument("--docs-checked", default="", choices=["","yes","no","not_applicable"], help="docs updated for changed subsystems")
    p_rrv.add_argument("--root-cause", default="", choices=["","fixed","symptom_only","not_applicable"], help="whether fix addressed root cause")
    p_rrv.add_argument("--summary", default="", help="short review evidence summary")
    p_rrv.add_argument("--context-id", default="", help="context ID")
    p_rrv.add_argument("--force", action="store_true", help="allow same-session review on L2+ (Planner inline execution only)")
    p_rrv.set_defaults(func=_cmd_record_review)
    p_re = p_state_sub.add_parser("record-role-evidence", help="record explicit role evidence when hooks cannot observe a subagent")
    p_re.add_argument("--role", required=True, choices=["executor","tester","reviewer","planner"], help="role that produced the evidence")
    p_re.add_argument("--summary", required=True, help="short evidence summary")
    p_re.add_argument("--command", default="", help="command or action observed")
    p_re.add_argument("--changed-file", action="append", default=[], dest="changed_files", help="repeatable changed file")
    p_re.add_argument("--session-id", default="", help="engine session id, if available")
    p_re.add_argument("--agent-id", default="", help="subagent id, if available")
    p_re.add_argument("--agent-type", default="", help="agent type, if available")
    p_re.add_argument("--context-id", default="", help="context ID")
    p_re.add_argument("--status", default="pending", choices=["pending","accepted","rejected"], help="initial evidence status")
    p_re.add_argument("--exit-code", default=0, type=int, help="command exit code")
    p_re.add_argument("--scan-git", action="store_true", help="attach current git working-tree changed files as corroborating evidence")
    p_re.add_argument("--supports-plan", default="", dest="supports_plan", help="PLAN-ID this role evidence supports")
    p_re.add_argument("--supports-goal", default="", dest="supports_goal", help="GOAL-ID this role evidence supports")
    p_re.set_defaults(func=_cmd_record_role_evidence)
    p_mcf = p_state_sub.add_parser("mark-cleanup-fresh", help="mark cleanup as fresh, clear stale items")
    p_mcf.add_argument("--note", action="append", default=[], dest="notes", help="repeatable resolved notes")
    p_mcf.set_defaults(func=_cmd_mark_cleanup_fresh)
    p_mcs = p_state_sub.add_parser("mark-cleanup-stale", help="mark cleanup as stale with items/blockers")
    p_mcs.add_argument("--stale-item", action="append", required=True, default=[], dest="stale_items", help="repeatable stale items")
    p_mcs.add_argument("--blocker", action="append", default=[], dest="blockers", help="repeatable blockers")
    p_mcs.add_argument("--note", action="append", default=[], dest="notes", help="repeatable notes")
    p_mcs.set_defaults(func=_cmd_mark_cleanup_stale)
    # ── cleanup check ──
    p_cc = sub.add_parser("cleanup", help="lifecycle cleanup check (check)")
    p_cc_sub = p_cc.add_subparsers(dest="cleanup_cmd")
    p_cc_sub.add_parser("check", help="run lifecycle cleanup check (read-only)").set_defaults(func=_cmd_cleanup_check)
    p_cc.set_defaults(func=_cmd_cleanup_check)
    p_pc = p_state_sub.add_parser("prepare-close", help="run authoritative closure gate checks (testing, review, evidence, cleanup)")
    p_cc = p_state_sub.add_parser("cancel-close", help="cancel close attempt — resets close_attempt + phase, unblocks task activation")
    p_cc.set_defaults(func=_cmd_cancel_close)
    p_pc.set_defaults(func=_cmd_prepare_close)
    p_gc = p_state_sub.add_parser("set-goal-confirmed", help="toggle goal confirmation; L1+ blocks activation when unconfirmed")
    p_gc.add_argument("--confirmed", required=True, choices=["true", "false"], help="true = user confirmed, false = needs confirmation")
    p_gc.set_defaults(func=_cmd_set_goal_confirmed)
    p_pi = p_state_sub.add_parser("set-planner-inline", help="record Planner decision to execute inline (waives session diversity gate)")
    p_pi.add_argument("--reason", required=True, help="why this task was executed inline instead of via independent subagents")
    p_pi.set_defaults(func=_cmd_set_planner_inline)
    p_da = p_state_sub.add_parser("disposition-adversarial", help="disposition a single adversarial observation")
    p_da.add_argument("--id", required=True, dest="adv_id", help="adversarial observation ID (e.g. ADV-001)")
    p_da.add_argument("--disposition", required=True, choices=["ignored","accepted","deferred","brief_updated","resolved"], help="disposition")
    p_da.add_argument("--reason", required=True, help="disposition reason")
    p_da.add_argument("--disposed-by", default="planner", dest="disposed_by", help="who is disposing")
    p_da.set_defaults(func=_cmd_disposition_adversarial)
    p_mc = p_state_sub.add_parser("record-meta-critique", help="record structured Planner meta-critique")
    p_mc.add_argument("--summary", required=True, help="what the Planner concluded after reviewing adversarial observations")
    p_mc.set_defaults(func=_cmd_record_meta_critique)
    p_ar = p_state_sub.add_parser("record-architecture-review", help="record periodic architecture review outcome")
    p_ar.add_argument("--task-id", required=True, help="active ARCH-* review task")
    p_ar.add_argument("--status", required=True, choices=["intact", "issues_found"])
    p_ar.add_argument("--issue", action="append", default=[], help="repeatable SEVERITY:::DESCRIPTION")
    p_ar.add_argument("--summary", default="", help="architecture review summary")
    p_ar.add_argument("--resolution", default="", help="required when clearing prior issues")
    p_ar.add_argument("--resolution-evidence-id", action="append", default=[], dest="resolution_evidence_ids")
    p_ar.add_argument("--resolved-task-id", action="append", default=[], dest="resolved_task_ids")
    p_ar.set_defaults(func=_cmd_record_architecture_review)
    p_swm = p_state_sub.add_parser("set-workflow-mode", help="record uncertainty routing mode/pattern")
    p_swm.add_argument("--request-mode", required=True, choices=["discussion","clarification","research","spike","execution"], help="current request mode")
    p_swm.add_argument("--workflow-pattern", default="", choices=["","linear","clarification_first","research_first","spike_first","adversarial_early"], help="uncertainty handling pattern")
    p_swm.add_argument("--reason", default="", help="short reason")
    p_swm.add_argument("--external-research-required", action="store_true", help="flag external research requirement")
    p_swm.set_defaults(func=_cmd_set_workflow_mode)
    p_state.set_defaults(func=_cmd_state_help)
    # ── route override (V2-A) ──
    p_route = sub.add_parser("route", help="routing override and explanation (V2-A topology operations)")
    p_route_sub = p_route.add_subparsers(dest="route_cmd")
    p_route_sub.add_parser("explain", help="explain current routing decision").set_defaults(func=_cmd_route_explain)
    p_rd = p_route_sub.add_parser("downgrade", help="request topology downgrade with recorded reason")
    p_rd.add_argument("--to", required=True,
                      choices=["single_agent", "single_agent_with_machine_evidence",
                               "light_review", "standard_team", "fanout_merge"],
                      help="target execution topology")
    p_rd.add_argument("--task-id", default="", help="task this downgrade applies to")
    p_rd.add_argument("--reason", required=True, help="why downgrade is safe for this task")
    p_rd.add_argument("--substitute", default="", help="alternative verification that replaces the waived topology")
    p_rd.add_argument("--user-confirmed", action="store_true",
                      help="user explicitly approved this downgrade after seeing the tradeoff")
    p_rd.set_defaults(func=_cmd_route_downgrade)
    p_rs = p_route_sub.add_parser("substitute", help="waive topology requirement with alternative verification")
    p_rs.add_argument("--use", required=True,
                      choices=["single_agent", "single_agent_with_machine_evidence",
                               "light_review", "standard_team", "fanout_merge"],
                      help="alternative execution topology to use")
    p_rs.add_argument("--task-id", default="", help="task this substitution applies to")
    p_rs.add_argument("--waive", required=True, help="what topology requirement is being waived")
    p_rs.add_argument("--reason", required=True, help="why the alternative is sufficient")
    p_rs.add_argument("--substitute", required=True, help="alternative verification that replaces the waived requirement")
    p_rs.add_argument("--user-confirmed", action="store_true",
                      help="user explicitly approved this substitution after seeing the tradeoff")
    p_rs.set_defaults(func=_cmd_route_substitute)
    p_route.set_defaults(func=_cmd_route_help)
    # ── claim-evidence alignment ──
    p_claim = sub.add_parser("claim", help="claim-evidence alignment (record, verify, list)")
    p_claim_sub = p_claim.add_subparsers(dest="claim_cmd")
    p_clr = p_claim_sub.add_parser("record", help="record a claim linked to evidence")
    p_clr.add_argument("--text", required=True, help="claim text (what is being asserted)")
    p_clr.add_argument("--task-id", default="", help="task this claim belongs to")
    p_clr.add_argument("--evidence-id", action="append", default=[], dest="evidence_ids", help="repeatable evidence ID backing this claim")
    p_clr.add_argument("--claim-id", default="", help="custom claim ID (auto-generated if omitted)")
    p_clr.set_defaults(func=_cmd_claim_record)
    p_clv = p_claim_sub.add_parser("verify", help="auto-verify claim-evidence alignment")
    p_clv.add_argument("--task-id", default="", help="only verify claims for this task")
    p_clv.set_defaults(func=_cmd_claim_verify)
    p_cll = p_claim_sub.add_parser("list", help="list claims")
    p_cll.add_argument("--task-id", default="", help="filter by task")
    p_cll.set_defaults(func=_cmd_claim_list)
    p_claim.set_defaults(func=_cmd_claim_help)
    # ── change admission ──
    p_change = sub.add_parser("change", help="change admission — entry judgment for new work (Stage 4)")
    p_change_sub = p_change.add_subparsers(dest="change_cmd")
    p_ca = p_change_sub.add_parser("admit", help="recommend admission path for a new change")
    p_ca.add_argument("--summary", required=True, help="one-line description of the proposed change")
    p_ca.add_argument("--target-goal", default="", dest="target_goal",
                      help="hint: preferred target goal ID (optional)")
    p_ca.add_argument("--debug", action="store_true", default=False,
                      help="show detected signals and scoring")
    p_ca.set_defaults(func=_cmd_change_admit)
    p_cv = p_change_sub.add_parser("validate-decision", help="validate an Admission Decision JSON (Stage 4.2)")
    p_cv.add_argument("--file", default="", help="path to admission decision JSON file (reads from stdin if omitted)")
    p_cv.set_defaults(func=_cmd_change_validate_decision)
    p_cn = p_change_sub.add_parser("prepare", help="prepare a reviewable Action Plan from an Admission Decision (Stage 4.3)")
    p_cn.add_argument("--file", default="", help="path to admission decision JSON file (reads from stdin if omitted)")
    p_cn.add_argument("--json", action="store_true", default=False, dest="json_output",
                      help="output full JSON (human_action_plan + operation_plan)")
    p_cn.set_defaults(func=_cmd_change_prepare)
    p_change.set_defaults(func=_cmd_change_help)
    # ── execution frontier (Stage 4.7) ──
    p_frontier = sub.add_parser("frontier", help="execution frontier — semantic dispatch + Work Packet (Stage 4.7)")
    p_frontier_sub = p_frontier.add_subparsers(dest="frontier_cmd")
    p_fv = p_frontier_sub.add_parser("validate", help="validate a Frontier Decision JSON")
    p_fv.add_argument("--file", default="", help="path to frontier decision JSON file (reads from stdin if omitted)")
    p_fv.set_defaults(func=_cmd_frontier_validate)
    p_fp = p_frontier_sub.add_parser("prepare", help="prepare a Work Packet from a Frontier Decision")
    p_fp.add_argument("--file", default="", help="path to frontier decision JSON file (reads from stdin if omitted)")
    p_fp.add_argument("--json", action="store_true", default=False, dest="json_output",
                      help="output Agent Work Packet as JSON")
    p_fp.set_defaults(func=_cmd_frontier_prepare)
    p_frontier.set_defaults(func=_cmd_frontier_help)
    # ── task plan artifacts ──
    p_plan = sub.add_parser("plan", help="task plan artifacts (create, update, show, summarize, list)")
    p_plan_sub = p_plan.add_subparsers(dest="plan_cmd")
    p_plc = p_plan_sub.add_parser("create", help="create .aiwf/artifacts/plans/PLAN.md (or legacy TASK.md)")
    p_plc.add_argument("plan_id_pos", nargs="?", help="plan ID")
    p_plc.add_argument("--plan-id", default="", help="plan ID")
    p_plc.add_argument("--task-id", default="", help="legacy task ID / optional task to attach")
    p_plc.add_argument("--task", action="append", default=[], dest="task_ids", help="repeatable task ID to attach")
    p_plc.add_argument("--goal-id", default="", help="goal ID (default GOAL-001)")
    p_plc.add_argument("--target-goal", default="", dest="target_goal_id",
                       help="target Goal this Plan attaches to (future authority; defaults to --goal-id)")
    p_plc.add_argument("--kind", default="", dest="plan_kind",
                       choices=["", "structural", "implementation", "verification", "migration", "exploration"],
                       help="plan kind (default implementation)")
    p_plc.add_argument("--active-phase", default="", dest="active_phase",
                       choices=["", "framing", "implementation", "integration", "seal"],
                       help="plan active phase (default implementation)")
    p_plc.add_argument("--work-intent", default="", dest="work_intent",
                       choices=["", "feature", "bugfix", "refactor", "cleanup", "migration",
                                "verification", "exploration", "documentation", "integration", "release"],
                       help="work intent (behavioral discipline)")
    p_plc.add_argument("--interface", action="append", default=[], dest="interfaces",
                       help="repeatable plan interface description")
    p_plc.add_argument("--constraint", action="append", default=[], dest="constraints",
                       help="repeatable plan constraint")
    p_plc.add_argument("--child-goal-policy", default="", dest="child_goal_policy",
                       help="policy for child goals under this plan")
    p_plc.add_argument("--milestone-id", default="", help="optional milestone ID")
    p_plc.add_argument("--context-id", default="", help="context ID")
    p_plc.add_argument("--title", default="", help="plan title")
    p_plc.add_argument("--allowed-write", action="append", default=[], dest="allowed_write",
                       help="repeatable allowed write path (scope boundary)")
    p_plc.add_argument("--forbidden-write", action="append", default=[], dest="forbidden_write",
                       help="repeatable forbidden write path")
    p_plc.add_argument("--purpose", default="", help="plan purpose (one-line intent)")
    p_plc.add_argument("--test-focus", action="append", default=[], dest="test_focus",
                       help="repeatable test focus hint")
    p_plc.add_argument("--review-focus", action="append", default=[], dest="review_focus",
                       help="repeatable review focus hint")
    p_plc.add_argument("--interface-contract", default="", help="interface contract description")
    p_plc.add_argument("--escalation-trigger", action="append", default=[], dest="escalation_triggers",
                       help="repeatable escalation trigger")
    p_plc.add_argument("--depends-on", action="append", default=None,
                       help="require another Plan to be complete before activation")
    p_plc.set_defaults(func=_cmd_plan_create)
    p_plu = p_plan_sub.add_parser("update", help="update one plan section")
    p_plu.add_argument("--task-id", required=True, help="task ID")
    p_plu.add_argument("--section", required=True, choices=["goal","route","scope","risks","decision","verification","impact","docs-assets","done-means","goal-progress","next-steps","open-questions","decisions","implementation","testing","review","evidence","checklist"], help="section key (new: goal/route/scope/risks/decision/verification/impact(docs-assets)/done-means/goal-progress/next-steps; old names map to new)")
    p_plu.add_argument("--content", required=True, help="replacement section content")
    p_plu.set_defaults(func=_cmd_plan_update)
    p_pls = p_plan_sub.add_parser("show", help="show one task plan")
    p_pls.add_argument("task_id", help="task ID")
    p_pls.set_defaults(func=_cmd_plan_show)
    p_plsum = p_plan_sub.add_parser("summarize", help="summarize one task plan")
    p_plsum.add_argument("task_id", help="task ID")
    p_plsum.set_defaults(func=_cmd_plan_summarize)
    p_pla = p_plan_sub.add_parser("attach", help="attach a task to a plan registry entry")
    p_pla.add_argument("plan_id", help="plan ID")
    p_pla.add_argument("task_id", help="task ID")
    p_pla.set_defaults(func=_cmd_plan_attach)
    p_pld = p_plan_sub.add_parser("detach", help="detach a task from a plan registry entry")
    p_pld.add_argument("plan_id", help="plan ID")
    p_pld.add_argument("task_id", help="task ID")
    p_pld.set_defaults(func=_cmd_plan_detach)
    p_plan_sub.add_parser("list", help="list task plans").set_defaults(func=_cmd_plan_list)
    p_pla_act = p_plan_sub.add_parser("activate", help="activate a plan — set as active_plan_id")
    p_pla_act.add_argument("plan_id", help="plan ID to activate")
    p_pla_act.set_defaults(func=_cmd_plan_activate)
    p_pla_de = p_plan_sub.add_parser("deactivate", help="deactivate the active plan")
    p_pla_de.set_defaults(func=_cmd_plan_deactivate)
    p_pldep = p_plan_sub.add_parser("dep", help="manage Plan execution dependencies")
    p_pldep_sub = p_pldep.add_subparsers(dest="plan_dep_cmd", required=True)
    p_pldep_add = p_pldep_sub.add_parser("add", help="add a Plan dependency")
    p_pldep_add.add_argument("plan_id")
    p_pldep_add.add_argument("dependency_id")
    p_pldep_add.set_defaults(func=_cmd_plan_dep_add)
    p_pldep_remove = p_pldep_sub.add_parser("remove", help="remove a Plan dependency")
    p_pldep_remove.add_argument("plan_id")
    p_pldep_remove.add_argument("dependency_id")
    p_pldep_remove.add_argument("--reason", required=True)
    p_pldep_remove.set_defaults(func=_cmd_plan_dep_remove)
    p_pldep_show = p_pldep_sub.add_parser("show", help="show Plan dependency readiness")
    p_pldep_show.add_argument("plan_id")
    p_pldep_show.set_defaults(func=_cmd_plan_dep_show)
    p_plan.set_defaults(func=_cmd_plan_help)
    # ── mission ──
    p_mis = sub.add_parser("mission", help="project-level mission — semantic container above the Goal Tree")
    p_mis_sub = p_mis.add_subparsers(dest="mission_cmd")
    p_mis_sub.add_parser("show", help="show current mission").set_defaults(func=_cmd_mission_show)
    p_misu = p_mis_sub.add_parser("update", help="update mission statement or boundaries")
    p_misu.add_argument("--statement", default=None, help="mission statement — why this project exists")
    p_misu.add_argument("--boundary", action="append", default=None, dest="boundary",
                       help="repeatable: project boundary — what we do NOT do")
    p_misu.add_argument("--status", default="", help="mission status (draft/active/complete/archived)")
    p_misu.add_argument("--add-milestone", default="", dest="add_milestone", help="attach a milestone ID")
    p_misu.add_argument("--add-goal-root", default="", dest="add_goal_root", help="attach a goal tree root ID")
    p_misu.set_defaults(func=_cmd_mission_update)
    p_mis.set_defaults(func=_cmd_mission_help)
    # ── optional milestone nodes ──
    p_ms = sub.add_parser("milestone", help="optional milestone nodes for long tasks")
    p_ms_sub = p_ms.add_subparsers(dest="milestone_cmd")
    p_msc = p_ms_sub.add_parser("create", help="create a milestone node")
    p_msc.add_argument("milestone_id", help="milestone ID, e.g. MS-001")
    p_msc.add_argument("--goal-id", default="", help="goal ID (default GOAL-001)")
    p_msc.add_argument("--title", default="", help="milestone title")
    p_msc.add_argument("--status", default="pending", choices=["pending","active","complete_candidate","completed","archived"], help="milestone status")
    p_msc.add_argument("--intent", default="", help="stage outcome intent")
    p_msc.add_argument("--plan", action="append", default=[], dest="plan_ids", help="repeatable plan ID")
    p_msc.add_argument("--task", action="append", default=[], dest="task_ids", help="repeatable task ID")
    p_msc.add_argument("--advance-policy", default="", choices=["","auto","checkpoint","manual"], help="advance policy")
    p_msc.add_argument("--checkpoint-level", default="", choices=["","task","plan","milestone","goal"], help="checkpoint level")
    p_msc.add_argument("--mission-id", default="", help="owning mission ID")
    p_msc.add_argument("--covered-goal", action="append", default=[], dest="covered_goal_ids",
                       help="repeatable goal ID covered by this milestone")
    p_msc.set_defaults(func=_cmd_milestone_create)
    p_ms_sub.add_parser("list", help="list milestones").set_defaults(func=_cmd_milestone_list)
    p_mss = p_ms_sub.add_parser("show", help="show one milestone")
    p_mss.add_argument("milestone_id", help="milestone ID")
    p_mss.set_defaults(func=_cmd_milestone_show)
    p_msu = p_ms_sub.add_parser("update", help="update a milestone node")
    p_msu.add_argument("milestone_id", help="milestone ID")
    p_msu.add_argument("--goal-id", default="", help="goal ID")
    p_msu.add_argument("--title", default="", help="milestone title")
    p_msu.add_argument("--status", default="", choices=["","pending","active","complete_candidate","completed","archived"], help="milestone status")
    p_msu.add_argument("--intent", default="", help="stage outcome intent")
    p_msu.add_argument("--plan", action="append", default=[], dest="plan_ids", help="repeatable plan ID")
    p_msu.add_argument("--task", action="append", default=[], dest="task_ids", help="repeatable task ID")
    p_msu.add_argument("--advance-policy", default="", choices=["","auto","checkpoint","manual"], help="advance policy")
    p_msu.add_argument("--checkpoint-level", default="", choices=["","task","plan","milestone","goal"], help="checkpoint level")
    p_msu.set_defaults(func=_cmd_milestone_update)
    p_msa = p_ms_sub.add_parser("assess", help="record milestone stage synthesis")
    p_msa.add_argument("milestone_id", help="milestone ID")
    p_msa.add_argument("--verdict", required=True, choices=["PASS","PASS_WITH_RISK","REVISE","REJECT"], help="stage synthesis verdict")
    p_msa.add_argument("--summary", required=True, help="stage synthesis summary")
    p_msa.add_argument("--evidence-id", action="append", default=[], dest="evidence_ids", help="repeatable evidence ID")
    p_msa.add_argument("--coherence-check", default="", help="stage coherence judgment")
    p_msa.add_argument("--open-gap", action="append", default=[], dest="open_gaps", help="repeatable open gap")
    p_msa.add_argument("--residual-risk", action="append", default=[], dest="residual_risks", help="repeatable residual risk")
    p_msa.add_argument("--next-recommendation", default="", help="recommended next stage/action")
    p_msa.set_defaults(func=_cmd_milestone_assess)
    p_msi = p_ms_sub.add_parser("integration-test", help="record milestone integration test")
    p_msi.add_argument("milestone_id", help="milestone ID")
    p_msi.add_argument("--status", required=True, choices=["passed","failed"], help="integration test status")
    p_msi.add_argument("--command", action="append", default=[], dest="command",
                       help="repeatable: 'cmd ::: output_summary'")
    p_msi.add_argument("--summary", default="", help="test summary")
    p_msi.add_argument("--failed-point", action="append", default=[], dest="failed_point",
                       help="repeatable failed integration point names")
    p_msi.add_argument("--coverage-mode", choices=["function_reverse_trace"], default="",
                       help="required for passed: exhaustive per-function reverse trace")
    p_msi.add_argument("--main-path-status", choices=["passed","failed","not_run"], default="",
                       help="actual end-to-end main path result")
    p_msi.add_argument("--source-file", action="append", default=[],
                       help="repeatable source file in the audited universe")
    p_msi.add_argument("--accounted-file", action="append", default=[],
                       help="repeatable source file with no callable functions or otherwise accounted for")
    p_msi.add_argument("--function-trace", action="append", default=[],
                       help="repeatable FILE::FUNCTION::CALLERS::STATUS[::REASON]")
    p_msi.set_defaults(func=_cmd_milestone_integration_test)
    p_msr = p_ms_sub.add_parser("arch-review", help="record milestone architecture review")
    p_msr.add_argument("milestone_id", help="milestone ID")
    p_msr.add_argument("--status", required=True, choices=["intact","issues_found"], help="arch review status")
    p_msr.add_argument("--interface", action="append", default=[], dest="interface",
                       help="repeatable: 'FROM_GOAL→TO_GOAL'")
    p_msr.add_argument("--issue", action="append", default=[], dest="issue",
                       help="repeatable SEVERITY:::DESCRIPTION (critical|high|medium|low)")
    p_msr.add_argument("--notes", default="", help="review notes")
    p_msr.add_argument("--resolution", default="",
                       help="required when clearing a prior issues_found review")
    p_msr.add_argument("--resolution-evidence-id", action="append", default=[],
                       help="repeatable evidence ID supporting the architecture fix")
    p_msr.set_defaults(func=_cmd_milestone_arch_review)
    p_msl = p_ms_sub.add_parser("close", help="close milestone after assessment")
    p_msl.add_argument("milestone_id", help="milestone ID")
    p_msl.set_defaults(func=_cmd_milestone_close)
    p_msconfirm = p_ms_sub.add_parser("confirm", help="record user acceptance after technical gates pass")
    p_msconfirm.add_argument("milestone_id", help="milestone ID")
    p_msconfirm.add_argument("--confirmed-by", default="user", help="who accepted the milestone")
    p_msconfirm.add_argument("--summary", required=True, help="what the user accepted")
    p_msconfirm.set_defaults(func=_cmd_milestone_confirm)
    p_ms.set_defaults(func=_cmd_milestone_help)
    # ── goal tree registry ──
    p_gt = sub.add_parser("goal-tree", help="recursive Goal Tree registry (Stage 3.2+)")
    p_gt_sub = p_gt.add_subparsers(dest="goal_tree_cmd")
    p_gti = p_gt_sub.add_parser("init-root", help="create a root Goal")
    p_gti.add_argument("goal_id", help="goal ID, e.g. GOAL-001")
    p_gti.add_argument("--type", default="main", choices=["main", "temporary", "branch"],
                       help="root type (default main)")
    p_gti.add_argument("--title", default="", help="goal title")
    p_gti.add_argument("--intent", default="", help="goal intent")
    p_gti.set_defaults(func=_cmd_goal_tree_init_root)
    p_gta = p_gt_sub.add_parser("add", help="add a child Goal")
    p_gta.add_argument("goal_id", help="child goal ID")
    p_gta.add_argument("--parent", required=True, dest="parent_id", help="parent goal ID")
    p_gta.add_argument("--title", default="", help="goal title")
    p_gta.add_argument("--intent", default="", help="goal intent")
    p_gta.set_defaults(func=_cmd_goal_tree_add)
    p_gts = p_gt_sub.add_parser("show", help="show goal tree or single goal")
    p_gts.add_argument("goal_id", nargs="?", default="", help="goal ID (omit for tree view)")
    p_gts.set_defaults(func=_cmd_goal_tree_show)
    p_gt_sub.add_parser("list", help="list all goals").set_defaults(func=_cmd_goal_tree_list)
    p_gt_sub.add_parser("list-temporary", help="list temporary root goals").set_defaults(func=_cmd_goal_tree_list_temporary)
    p_gt_sub.add_parser("validate", help="validate goal tree integrity").set_defaults(func=_cmd_goal_tree_validate)
    p_gtg = p_gt_sub.add_parser("graft", help="graft a branch into the main tree")
    p_gtg.add_argument("source_id", help="source goal/branch ID")
    p_gtg.add_argument("--target", required=True, dest="target_parent_id", help="target parent goal ID")
    p_gtg.add_argument("--reason", default="", help="reason for grafting")
    p_gtg.add_argument("--interface", default="", dest="interface_consumed",
                       help="which parent interface is consumed by this graft")
    p_gtg.add_argument("--provides", default="", dest="capability_provided",
                       help="what capability the grafted branch provides")
    p_gtg.add_argument("--relation-to-parent", default="", dest="relation_to_parent",
                       help="how the source relates to parent (e.g. extends, implements, replaces)")
    p_gtg.add_argument("--affected-plan", action="append", default=[], dest="affected_plans",
                       help="repeatable plan ID affected by this graft")
    p_gtg.add_argument("--parent-meaning-changes", action="store_true", dest="parent_meaning_changes",
                       help="this graft changes the parent's meaning")
    p_gtg.set_defaults(func=_cmd_goal_tree_graft)
    p_gtp = p_gt_sub.add_parser("prune", help="archive a branch")
    p_gtp.add_argument("branch_id", help="branch goal ID to prune")
    p_gtp.add_argument("--reason", default="", help="reason for pruning")
    p_gtp.set_defaults(func=_cmd_goal_tree_prune)
    p_gti_impact = p_gt_sub.add_parser("impact", help="show Impact Cone for a goal")
    p_gti_impact.add_argument("goal_id", help="goal ID")
    p_gti_impact.set_defaults(func=_cmd_goal_tree_impact)
    # Stage 4.5: Day-1 Foundation Tree validation
    p_gtf = p_gt_sub.add_parser("validate-foundation", help="validate a Day-1 Foundation Tree proposal (Stage 4.5)")
    p_gtf.add_argument("--file", default="", help="path to foundation tree JSON file (reads from stdin if omitted)")
    p_gtf.add_argument("--json", action="store_true", default=False, dest="json_output",
                       help="output as JSON")
    p_gtf.set_defaults(func=_cmd_foundation_validate)
    p_gt.set_defaults(func=_cmd_goal_tree_help)
    # ── sibling relations ──
    p_rel = sub.add_parser("relation", help="sibling relations between goals")
    p_rel_sub = p_rel.add_subparsers(dest="relation_cmd")
    p_ra = p_rel_sub.add_parser("add", help="add a sibling relation")
    p_ra.add_argument("source_id", help="source goal ID")
    p_ra.add_argument("target_id", help="target goal ID")
    p_ra.add_argument("rel_type", choices=["depends_on", "blocks", "conflicts_with", "invalidates", "supports"],
                      help="relation type")
    p_ra.add_argument("--reason", default="", help="reason for relation")
    p_ra.add_argument("--cross", action="store_true", default=False,
                      help="allow cross-parent relation (default: same parent required)")
    p_ra.set_defaults(func=_cmd_relation_add)
    p_rr = p_rel_sub.add_parser("remove", help="remove a sibling relation")
    p_rr.add_argument("source_id", help="source goal ID")
    p_rr.add_argument("target_id", help="target goal ID")
    p_rr.set_defaults(func=_cmd_relation_remove)
    p_rs = p_rel_sub.add_parser("show", help="show relations for a node")
    p_rs.add_argument("node_id", help="goal ID")
    p_rs.set_defaults(func=_cmd_relation_show)
    p_rel.set_defaults(func=_cmd_relation_show)
    p_task = sub.add_parser("task", help="flexible task ledger and execution-window gate")
    p_task_sub = p_task.add_subparsers(dest="task_cmd")
    p_tp = p_task_sub.add_parser("plan", help="create/update a ledger task without activating execution")
    p_tp.add_argument("task_id_pos", nargs="?", help="task ID, e.g. TASK-001")
    p_tp.add_argument("--task-id", default="", help="task ID, e.g. TASK-001")
    p_tp.add_argument("--title", default="", help="task title")
    p_tp.add_argument("--status", default="candidate", choices=["candidate","ready","active","blocked","suspended","closed","rejected"], help="task status")
    p_tp.add_argument("--dependency", action="append", default=[], dest="dependencies", help="repeatable dependency task ID")
    p_tp.add_argument("--allowed-write", action="append", default=[], dest="allowed_write",
                      help="deprecated and ignored; define scope with aiwf plan create --allowed-write")
    p_tp.add_argument("--parallel-safe", action="store_true", help="Planner verified independent parallel execution")
    p_tp.add_argument("--note", action="append", default=[], dest="notes", help="repeatable task note")
    p_tp.add_argument("--parent-goal", default="", dest="parent_goal", help="GOAL-ID this task serves")
    p_tp.add_argument("--parent-plan", default="", dest="parent_plan", help="PLAN-ID this task belongs to")
    p_tp.add_argument("--goal", default="", dest="goal_id", help="GOAL-ID this task serves")
    p_tp.add_argument("--plan", default="", dest="plan_id", help="PLAN-ID this task belongs to")
    p_tp.add_argument("--milestone", default="", help="legacy milestone label")
    p_tp.add_argument("--milestone-id", default="", help="optional milestone ID")
    p_tp.set_defaults(func=_cmd_task_plan)
    p_ta = p_task_sub.add_parser("activate", help="activate a task if execution-window gates pass")
    p_ta.add_argument("task_id", help="task ID")
    p_ta.add_argument("--skip-start-gate", action="store_true",
                      help="internal/test escape hatch; prefer task confirm-start or skip with reason")
    p_ta.set_defaults(func=_cmd_task_activate)
    p_tcs = p_task_sub.add_parser("confirm-start", help="record brief user-visible start confirmation before activation")
    p_tcs.add_argument("task_id", help="task ID")
    p_tcs.add_argument("--summary", default="", help="brief scope/risk/verification summary shown to the user")
    p_tcs.add_argument("--confirmed-by", default="user", help="who confirmed the start")
    p_tcs.add_argument("--skip", action="store_true", help="user explicitly asked not to receive a start report")
    p_tcs.add_argument("--reason", default="", help="required with --skip")
    p_tcs.set_defaults(func=_cmd_task_confirm_start)
    p_tc = p_task_sub.add_parser("close", help="mark a ledger task closed")
    p_tc.add_argument("task_id", help="task ID")
    p_tc.add_argument("--note", default="", help="closure note")
    p_tc.set_defaults(func=_cmd_task_close)
    p_ts = p_task_sub.add_parser("suspend", help="suspend a task with a lightweight state snapshot")
    p_ts.add_argument("task_id", help="task ID")
    p_ts.add_argument("--note", default="", help="suspension note")
    p_ts.set_defaults(func=_cmd_task_suspend)
    p_task_sub.add_parser("status", help="show task ledger summary").set_defaults(func=_cmd_task_status)
    p_task.set_defaults(func=_cmd_task_help)
    # ── fix-loop ──
    p_fixloop = sub.add_parser("fixloop", help="open or resolve a fix-loop")
    p_fl_sub = p_fixloop.add_subparsers(dest="fixloop_cmd")
    p_fl_open = p_fl_sub.add_parser("open", help="open a fix-loop with route and required fixes")
    p_fl_open.add_argument("--route", required=True, choices=["executor","tester","planner","environment"], help="route the fix to executor/tester/planner/environment")
    p_fl_open.add_argument("--reason", required=True, help="reason for opening the fix-loop")
    p_fl_open.add_argument("--required-fix", action="append", default=[], dest="required_fixes", help="repeatable required fixes")
    p_fl_open.add_argument("--required-verification", action="append", default=[], dest="required_verification", help="repeatable required verification steps")
    p_fl_open.add_argument("--invalidated-file", action="append", default=[], dest="invalidated_files", help="repeatable files invalidated by this fix-loop")
    p_fl_open.add_argument("--invalidated-obligation", action="append", default=[], dest="invalidated_obligations", help="repeatable obligations invalidated by this fix-loop")
    p_fl_open.add_argument("--invalidated-evidence", action="append", default=[], dest="invalidated_evidence_ids", help="repeatable evidence IDs invalidated by this fix-loop")
    p_fl_open.add_argument("--source", default="reviewer", help="who opened the fix-loop (default: reviewer)")
    p_fl_open.set_defaults(func=_cmd_fix_loop_open)
    p_fl_resolve = p_fl_sub.add_parser("resolve", help="resolve a fix-loop")
    p_fl_resolve.add_argument("--resolution", required=True, help="how the fix-loop was resolved")
    p_fl_resolve.add_argument("--source", default="reviewer", help="who resolved the fix-loop (default: reviewer)")
    p_fl_resolve.add_argument("--force", action="store_true", help="force resolution — Planner acknowledges remaining changed files are legitimate (cross-task modifications, not scope violations)")
    p_fl_resolve.set_defaults(func=_cmd_fix_loop_resolve)
    p_fl_status = p_fl_sub.add_parser("status", help="show fix-loop status")
    p_fl_status.set_defaults(func=_cmd_fix_loop_status)
    p_fl_repair = p_fl_sub.add_parser("repair", help="declare a repair target for the fix-loop repair window")
    p_fl_repair.add_argument("--target", required=True, help="file path to repair")
    p_fl_repair.add_argument("--reason", help="why this repair is needed")
    p_fl_repair.add_argument("--source", default="planner", help="who declared the repair")
    p_fl_repair.set_defaults(func=_cmd_fix_loop_repair)
    p_fl_reval = p_fl_sub.add_parser("revalidate", help="re-validate required_fixes against current git diff + review state")
    p_fl_reval.add_argument("--force", action="store_true", help="skip diff-unavailable checks")
    p_fl_reval.set_defaults(func=_cmd_fix_loop_revalidate)
    p_fixloop.set_defaults(func=_cmd_fix_loop_help)
    # ── arch-change ──
    p_ac = sub.add_parser("arch-change", help="architecture change requests (request, list, decide)")
    p_ac_sub = p_ac.add_subparsers(dest="arch_change_cmd")
    p_ac_req = p_ac_sub.add_parser("request", help="request an architecture change")
    p_ac_req.add_argument("--source", required=True, choices=["executor","tester","reviewer","planner"], help="who is requesting")
    p_ac_req.add_argument("--reason", required=True, help="why the change is needed")
    p_ac_req.add_argument("--proposed-change", required=True, dest="proposed_change", help="what is proposed")
    p_ac_req.add_argument("--affected-file", action="append", default=[], dest="affected_files", help="repeatable affected files")
    p_ac_req.add_argument("--affected-module", action="append", default=[], dest="affected_modules", help="repeatable affected modules")
    p_ac_req.add_argument("--current-contract-gap", default="", dest="current_contract_gap", help="gap in current contract")
    p_ac_req.add_argument("--scope-impact", default="", dest="scope_impact", help="scope impact")
    p_ac_req.add_argument("--risk", default="", help="risk of the change")
    p_ac_req.add_argument("--user-decision-required", action="store_true", dest="user_decision_required", help="flag if user decision needed")
    p_ac_req.set_defaults(func=_cmd_arch_change_request)
    p_ac_list = p_ac_sub.add_parser("list", help="list architecture change requests")
    p_ac_list.set_defaults(func=_cmd_arch_change_list)
    p_ac_dec = p_ac_sub.add_parser("decide", help="decide on an architecture change request")
    p_ac_dec.add_argument("id", help="ACR ID (e.g. ACR-001)")
    p_ac_dec.add_argument("--status", required=True, choices=["approved","rejected","superseded"], help="decision status")
    p_ac_dec.add_argument("--decision", required=True, help="planner decision text")
    p_ac_dec.set_defaults(func=_cmd_arch_change_decide)
    p_ac.set_defaults(func=_cmd_arch_change_help)
    p_cap = sub.add_parser("capability", help="external capability registry (scan, list, show)")
    p_cap_sub = p_cap.add_subparsers(dest="cap_cmd")
    p_cap_sub.add_parser("scan", help="scan project for external capabilities, write registry").set_defaults(func=_cmd_capability_scan)
    p_cap_sub.add_parser("list", help="list discovered capabilities").set_defaults(func=_cmd_capability_list)
    p_cap_show = p_cap_sub.add_parser("show", help="show one capability")
    p_cap_show.add_argument("id", help="capability ID")
    p_cap_show.set_defaults(func=_cmd_capability_show)
    p_cap_use = p_cap_sub.add_parser("plan-use", help="mark an external capability as intended for current-cycle use")
    p_cap_use.add_argument("id", help="capability ID")
    p_cap_use.set_defaults(func=_cmd_capability_plan_use)
    p_cap_dec = p_cap_sub.add_parser("decide", help="record Planner decision for lifecycle-overlap capability use")
    p_cap_dec.add_argument("id", help="capability ID")
    p_cap_dec.add_argument("--decision", required=True, help="Planner decision allowing/rejecting this capability use")
    p_cap_dec.add_argument("--decided-by", default="planner", help="who made the decision")
    p_cap_dec.set_defaults(func=_cmd_capability_decide)
    p_cap.set_defaults(func=_cmd_capability_scan)
    # ── recipes ──
    p_recipe = sub.add_parser("recipe", help="workflow recipes (list, show, recommend)")
    p_recipe_sub = p_recipe.add_subparsers(dest="recipe_cmd")
    p_recipe_sub.add_parser("list", help="list workflow recipes").set_defaults(func=_cmd_recipe_list)
    p_rs = p_recipe_sub.add_parser("show", help="show one workflow recipe")
    p_rs.add_argument("name", help="recipe name")
    p_rs.set_defaults(func=_cmd_recipe_show)
    p_rr = p_recipe_sub.add_parser("recommend", help="recommend recipes from task type and risk flags")
    p_rr.add_argument("--task-type", default="", help="task type key")
    p_rr.add_argument("--risk-flag", action="append", default=[], dest="risk_flags", help="repeatable risk flag")
    p_rr.set_defaults(func=_cmd_recipe_recommend)
    p_recipe.set_defaults(func=_cmd_recipe_help)
    # ── external research ──
    p_research = sub.add_parser("research", help="external research evidence (record, list, promote)")
    p_research_sub = p_research.add_subparsers(dest="research_cmd")
    p_xr = p_research_sub.add_parser("record", help="record low-trust external research")
    p_xr.add_argument("--source", required=True, help="source/tool/person")
    p_xr.add_argument("--query", required=True, help="research query/question")
    p_xr.add_argument("--claim", action="append", default=[], dest="claims", help="repeatable claim")
    p_xr.add_argument("--link", action="append", default=[], dest="links", help="repeatable link")
    p_xr.add_argument("--time-window", default="", help="time window such as last30days")
    p_xr.add_argument("--confidence", default="low", choices=["low","medium","high"], help="confidence")
    p_xr.set_defaults(func=_cmd_research_record)
    p_xl = p_research_sub.add_parser("list", help="list research records")
    p_xl.add_argument("--include-promoted", action="store_true", default=True, help="include promoted records")
    p_xl.set_defaults(func=_cmd_research_list)
    p_xp = p_research_sub.add_parser("promote", help="promote research into Planner decision trace")
    p_xp.add_argument("id", help="research ID")
    p_xp.add_argument("--decision", required=True, help="Planner decision using this research")
    p_xp.add_argument("--promoted-by", default="planner", help="who promoted it")
    p_xp.set_defaults(func=_cmd_research_promote)
    p_xs = p_research_sub.add_parser("skip", help="explicitly skip required external research")
    p_xs.add_argument("--reason", required=True, help="why external research is intentionally skipped")
    p_xs.add_argument("--decided-by", default="planner", help="who made the skip decision")
    p_xs.set_defaults(func=_cmd_research_skip)
    p_research.set_defaults(func=_cmd_research_help)
    # ── env ──
    p_env = sub.add_parser("env", help="project environment profile (scan, show)")
    p_env_sub = p_env.add_subparsers(dest="env_cmd")
    p_env_sub.add_parser("scan", help="scan project environment, write profile").set_defaults(func=_cmd_env_scan)
    p_env_sub.add_parser("show", help="show environment profile").set_defaults(func=_cmd_env_show)
    p_env.set_defaults(func=_cmd_env_help)
    # ── quality ──
    p_qual = sub.add_parser("quality", help="quality surface obligations (surfaces, surface)")
    p_qual_sub = p_qual.add_subparsers(dest="quality_cmd")
    p_qual_sub.add_parser("surfaces", help="list known quality surfaces").set_defaults(func=_cmd_quality_surfaces)
    p_qd = p_qual_sub.add_parser("digest", help="refresh cross-task quality digest")
    p_qd.add_argument("--force", action="store_true", help="bypass Impact quality_summary guard")
    p_qd.set_defaults(func=_cmd_quality_digest)
    p_qs = p_qual_sub.add_parser("surface", help="show obligations for a surface")
    p_qs.add_argument("name", help="surface name (e.g. api_endpoint)")
    p_qs.set_defaults(func=_cmd_quality_surface)
    p_qual.set_defaults(func=_cmd_quality_help)
    # ── idea ──
    p_idea = sub.add_parser("idea", help="idea inbox (capture, list, promote, expire)")
    p_idea_sub = p_idea.add_subparsers(dest="idea_cmd")
    p_ic = p_idea_sub.add_parser("capture", help="capture a new idea")
    p_ic.add_argument("--text", required=True, help="idea text (short)")
    p_ic.add_argument("--tag", action="append", default=[], dest="tags", help="repeatable tags")
    p_ic.add_argument("--source", default="user", help="source (default: user)")
    p_ic.add_argument("--expires-days", type=int, default=14, dest="expires_days", help="days until expiry (default: 14)")
    p_ic.set_defaults(func=_cmd_idea_capture)
    p_il = p_idea_sub.add_parser("list", help="list active ideas")
    p_il.add_argument("--include-expired", action="store_true", dest="include_expired", help="include expired ideas")
    p_il.set_defaults(func=_cmd_idea_list)
    p_ip = p_idea_sub.add_parser("promote", help="promote an idea to adopted")
    p_ip.add_argument("id", help="idea ID")
    p_ip.add_argument("--target", default="", help="promotion target (project-map/goal/decision/architecture/followup)")
    p_ip.add_argument("--note", default="", help="promotion note")
    p_ip.set_defaults(func=_cmd_idea_promote)
    p_ie = p_idea_sub.add_parser("expire", help="expire an idea")
    p_ie.add_argument("id", help="idea ID")
    p_ie.add_argument("--reason", default="", help="expiry reason")
    p_ie.set_defaults(func=_cmd_idea_expire)
    p_idea.set_defaults(func=_cmd_idea_help)
    # ── rule ──
    p_rule = sub.add_parser("rule", help="project rules (add, add-negative, list, retire, global-candidate)")
    p_rule_sub = p_rule.add_subparsers(dest="rule_cmd")
    p_ra = p_rule_sub.add_parser("add", help="add a project rule")
    p_ra.add_argument("--text", required=True, help="rule text")
    p_ra.add_argument("--source", default="", help="source/context")
    p_ra.add_argument("--tag", action="append", default=[], dest="tags", help="repeatable tags")
    p_ra.set_defaults(func=_cmd_rule_add)
    p_rn = p_rule_sub.add_parser("add-negative", help="add a negative rule / guardrail")
    p_rn.add_argument("--text", required=True, help="rule text")
    p_rn.add_argument("--source", default="", help="source/context")
    p_rn.add_argument("--tag", action="append", default=[], dest="tags", help="repeatable tags")
    p_rn.set_defaults(func=_cmd_rule_add_negative)
    p_rule_sub.add_parser("list", help="list active rules").set_defaults(func=_cmd_rule_list)
    p_rr = p_rule_sub.add_parser("retire", help="retire a rule")
    p_rr.add_argument("id", help="rule ID")
    p_rr.add_argument("--reason", default="", help="retirement reason")
    p_rr.set_defaults(func=_cmd_rule_retire)
    p_rg = p_rule_sub.add_parser("global-candidate", help="mark a rule as global lesson candidate")
    p_rg.add_argument("id", help="rule ID")
    p_rg.add_argument("--note", default="", help="candidate note")
    p_rg.set_defaults(func=_cmd_rule_global_candidate)
    p_rule.set_defaults(func=_cmd_rule_help)
    # ── project-map ──
    p_pm = sub.add_parser("project-map", help="project map and Goal-to-module bindings")
    p_pm_sub = p_pm.add_subparsers(dest="pm_cmd")
    p_pm_sub.add_parser("init", help="create PROJECT-MAP.md").set_defaults(func=_cmd_project_map_init)
    p_pm_sub.add_parser("show", help="display PROJECT-MAP.md").set_defaults(func=_cmd_project_map_show)
    p_pmb = p_pm_sub.add_parser("bootstrap", help="bootstrap AIWF assets from existing project code")
    p_pmb.set_defaults(func=_cmd_project_bootstrap)
    p_pmu = p_pm_sub.add_parser("update", help="update a section of PROJECT-MAP.md")
    p_pmu.add_argument("--section", required=True, choices=["snapshot","current-stage","completed-milestones","active-direction","next-candidate-tasks","architecture-direction","environment-summary","open-decisions","deferred-risks","rejected-routes","ideas-to-review"], help="section to update")
    p_pmu.add_argument("--text", required=True, help="new content for the section")
    p_pmu.set_defaults(func=_cmd_project_map_update)
    p_pm_sub.add_parser("summarize", help="show short summary of PROJECT-MAP.md").set_defaults(func=_cmd_project_map_summarize)
    p_pmbind = p_pm_sub.add_parser("bind", help="bind a Goal to repository modules")
    p_pmbind.add_argument("goal_id", help="Goal ID from goals.json")
    p_pmbind.add_argument("--module", action="append", required=True, dest="modules", help="repository-relative module path; repeatable")
    p_pmbind.add_argument("--entrypoint", action="append", default=[], dest="entrypoints", help="repository-relative entrypoint; repeatable")
    p_pmbind.add_argument("--interface", action="append", default=[], dest="interfaces", help="owned or exposed interface; repeatable")
    p_pmbind.add_argument("--note", default="", help="semantic ownership note")
    p_pmbind.set_defaults(func=_cmd_project_map_bind)
    p_pmunbind = p_pm_sub.add_parser("unbind", help="remove a Goal-to-module binding")
    p_pmunbind.add_argument("goal_id", help="Goal ID")
    p_pmunbind.add_argument("--reason", required=True, help="why the binding is removed")
    p_pmunbind.set_defaults(func=_cmd_project_map_unbind)
    p_pm_sub.add_parser("relations", help="show Goal-to-module bindings").set_defaults(func=_cmd_project_map_relations)
    p_pm_sub.add_parser("validate", help="validate Goal bindings against Goal Tree and repository").set_defaults(func=_cmd_project_map_validate)
    p_pm.set_defaults(func=_cmd_project_map_help)
    p_mem = sub.add_parser("memory", help="advisory lesson retrieval (suggest)")
    p_mem_sub = p_mem.add_subparsers(dest="mem_cmd")
    p_ms = p_mem_sub.add_parser("suggest", help="suggest relevant lessons for current task")
    p_ms.add_argument("--goal", default="", help="task goal for matching")
    p_ms.add_argument("--task-type", default="", help="task type key for matching")
    p_ms.add_argument("--file", action="append", default=[], dest="files", help="repeatable file paths")
    p_ms.add_argument("--limit", type=int, default=5, help="max results per category")
    p_ms.set_defaults(func=_cmd_memory_suggest)
    p_mem.set_defaults(func=_cmd_memory_help)
    p_git = sub.add_parser("git", help="git commit safety (summary, suggest, commit)")
    p_git_sub = p_git.add_subparsers(dest="git_cmd")
    p_git_sub.add_parser("summary", help="show git working tree summary").set_defaults(func=_cmd_git_summary)
    p_git_sub.add_parser("suggest-commit", help="suggest a commit message").set_defaults(func=_cmd_git_suggest)
    p_gc = p_git_sub.add_parser("commit", help="commit with confirmation (requires --confirm)")
    p_gc.add_argument("--message", required=True, help="commit message")
    p_gc.add_argument("--confirm", action="store_true", help="confirm commit")
    p_gc.add_argument("--include-governance", action="store_true", help="also commit governance files")
    p_gc.set_defaults(func=_cmd_git_commit)
    p_git.set_defaults(func=_cmd_git_summary)
    p_ck = sub.add_parser("checkpoint", help="rollback checkpoint (create, list, show, restore)")
    p_ck_sub = p_ck.add_subparsers(dest="ck_cmd")
    p_ck_cr = p_ck_sub.add_parser("create", help="create a rollback checkpoint")
    p_ck_cr.add_argument("--label", default="", help="checkpoint label")
    p_ck_cr.add_argument("--include-governance", dest="include_gov", action="store_true", default=True)
    p_ck_cr.add_argument("--no-include-governance", dest="include_gov", action="store_false")
    p_ck_cr.add_argument("--mode", choices=["patch","stash"], default="patch", help="checkpoint mode")
    p_ck_cr.set_defaults(func=_cmd_checkpoint_create)
    p_ck_sub.add_parser("list", help="list checkpoints").set_defaults(func=_cmd_checkpoint_list)
    p_ck_show = p_ck_sub.add_parser("show", help="show checkpoint metadata")
    p_ck_show.add_argument("id", help="checkpoint ID")
    p_ck_show.set_defaults(func=_cmd_checkpoint_show)
    p_ck_plan = p_ck_sub.add_parser("restore-plan", help="show restore plan")
    p_ck_plan.add_argument("id", help="checkpoint ID")
    p_ck_plan.set_defaults(func=_cmd_checkpoint_restore_plan)
    p_ck_restore = p_ck_sub.add_parser("restore", help="restore to checkpoint (requires --confirm)")
    p_ck_restore.add_argument("id", help="checkpoint ID")
    p_ck_restore.add_argument("--confirm", action="store_true", help="confirm restore")
    p_ck_restore.set_defaults(func=_cmd_checkpoint_restore)
    p_ck.set_defaults(func=_cmd_checkpoint_list)
    p_goal = sub.add_parser("goal", help="goal thread / intent revision operations")
    p_goal_sub = p_goal.add_subparsers(dest="goal_cmd")
    p_gr = p_goal_sub.add_parser("revise", help="revise current goal with intent tracking")
    p_gr.add_argument("--new-goal", required=True, help="new goal text")
    p_gr.add_argument("--reason", required=True, help="reason for revision")
    p_gr.add_argument("--decision", default="", help="associated decision")
    p_gr.add_argument("--source", default="user", help="source of revision")
    p_gr.set_defaults(func=_cmd_goal_revise)
    p_gd = p_goal_sub.add_parser("decide", help="record a goal-level decision")
    p_gd.add_argument("--decision", required=True, help="decision text")
    p_gd.add_argument("--source", default="user", help="source of decision")
    p_gd.set_defaults(func=_cmd_goal_decide)
    p_goal.set_defaults(func=_cmd_goal_help)
    p_ws = sub.add_parser("workspace", help="workspace drift scan")
    p_ws_sub = p_ws.add_subparsers(dest="ws_cmd")
    p_ws_scan = p_ws_sub.add_parser("scan", help="scan workspace for untracked/modified files")
    p_ws_scan.add_argument("--fix", action="store_true", help="auto-update baseline after detecting changes")
    p_ws_scan.set_defaults(func=_cmd_workspace_scan)
    p_ws_migrate = p_ws_sub.add_parser("migrate-layout", help="migrate workspace to v2 5-zone layout (Stage 4.7.3)")
    p_ws_migrate.add_argument("--dry-run", action="store_true", default=False, dest="dry_run",
                               help="show what would be moved without making changes")
    p_ws_migrate.set_defaults(func=_cmd_workspace_migrate_layout)
    p_ws.set_defaults(func=_cmd_workspace_scan)
    p_asset = sub.add_parser("asset", help="context asset layer commands (init, refresh)")
    p_asset_sub = p_asset.add_subparsers(dest="asset_cmd")
    p_asset_sub.add_parser("init", help="initialize .aiwf/assets/ with project-map, test-map, conventions").set_defaults(func=_cmd_asset_init)
    p_asset_refresh = p_asset_sub.add_parser("refresh", help="check or update asset freshness")
    p_asset_refresh.add_argument("--check", action="store_true", default=True, help="check freshness only (default)")
    p_asset_refresh.add_argument("--update", action="store_true", help="update hashes for changed files")
    p_asset_refresh.set_defaults(func=_cmd_asset_refresh)
    p_asset.set_defaults(func=_cmd_asset_init)
    p_audit = sub.add_parser("audit-archive", help="check a release zip for contaminants (.git, __MACOSX, .DS_Store, .pyc, __pycache__)")
    p_audit.add_argument("archive", help="path to the release zip")
    p_audit.set_defaults(func=_cmd_audit_archive)

    return parser
